import type { BomItemDetail, BomItemUpdateInput, Part } from '../Types/bom'
import {
  iplFeedingHasContent,
  type BomIplLogisticsInput,
  type BomIplFeedingCard
} from '../Utils/iplBomLogistics'
import { normalizePartNumber } from '../Utils/partNumberNormalize'
import { normalizeBomStationCodeText } from '../Utils/bomStationCode'
import {
  isAutoGeneratedPartNumber,
  isPartsListMaster,
  isPendingBomItemId,
  mergePartToBomItem,
  pendingBomItemId
} from '../Utils/iplModelParts'
import { listPartMastersLite } from './partsService'
import {
  bomRowAppliesToModel,
  parseApplicableModelNames
} from '../Utils/bomQtyByModel'
import {
  bomRowAssignedToIplModel,
  IPL_NOT_FITTED_PN,
  IPL_NOT_FITTED_QTY,
  IPL_NOT_FITTED_SHEET
} from '../Utils/iplFitStatus'
import { bomImportLineKey } from '../Utils/partNumberNormalize'
import { effectiveSupplySource } from '../Utils/bomDefaults'
import {
  client,
  logisticsPayload,
  pickLogisticsFields,
  isMissingColumnError,
  IPL_CORE_LOGISTICS_FIELDS,
  IPL_OPTIONAL_LOGISTICS_FIELDS,
  updateBomItem,
  deleteBomItem
} from './bomCrudService'
import { getBomItemsForPartIds } from './bomCrudService'

export async function updateBomGroupIplLogistics(itemIds: string[], logistics: BomIplLogisticsInput): Promise<void> {
  const realIds = itemIds.filter(id => id && !isPendingBomItemId(id))
  if (realIds.length === 0) return
  const payload = logisticsPayload(logistics)
  if (Object.keys(payload).length === 0) return
  const { error } = await client().from('bom_items').update(payload).in('id', realIds)
  if (error) throw new Error(error.message)
}

export async function updateBomIplFeedingCard(itemIds: string[], card: BomIplFeedingCard): Promise<void> {
  const realIds = itemIds.filter(id => id && !isPendingBomItemId(id))
  if (realIds.length === 0) return
  const payload = {
    ...logisticsPayload(card),
    stopper_type: card.stopper_type
  }
  const { error } = await client().from('bom_items').update(payload).in('id', realIds)
  if (error) throw new Error(error.message)

  const extra = pickLogisticsFields(card, IPL_OPTIONAL_LOGISTICS_FIELDS, true)
  if (Object.keys(extra).length === 0) return
  const extraRes = await client().from('bom_items').update(extra).in('id', realIds)
  if (extraRes.error && !isMissingColumnError(extraRes.error.message)) {
    throw new Error(extraRes.error.message)
  }
}

export async function updateIplModelLine(
  part: Pick<
    Part,
    'id' | 'part_number' | 'normalized_part_number' | 'part_name_ar' | 'part_name_en' | 'common_station'
  >,
  modelName: string,
  vehicleModelId: string,
  updates: { part_number?: string; quantity?: number; stationCode?: string; stationId?: string | null }
): Promise<string> {
  if (updates.part_number?.trim()) {
    const pn = updates.part_number.trim()
    const { error } = await client()
      .from('parts')
      .update({
        part_number: pn,
        normalized_part_number: normalizePartNumber(pn)
      })
      .eq('id', part.id)
    if (error) throw new Error(error.message)
    part = { ...part, part_number: pn, normalized_part_number: normalizePartNumber(pn) }
  }

  if (updates.stationCode !== undefined && !updates.part_number && updates.quantity == null) {
    const existingOnlyStation = await getBomItemsForPartIds([part.id], modelName)
    const existingRow = existingOnlyStation.get(part.id)
    if (!existingRow?.id || isPendingBomItemId(existingRow.id)) {
      const { error } = await client()
        .from('parts')
        .update({ common_station: normalizeBomStationCodeText(updates.stationCode) || null })
        .eq('id', part.id)
      if (error) throw new Error(error.message)
      return pendingBomItemId(part.id)
    }
  }

  const existingMap = await getBomItemsForPartIds([part.id], modelName)
  const existing = existingMap.get(part.id)
  const hasRealBom = Boolean(existing?.id && !isPendingBomItemId(existing.id))

  const realPn =
    updates.part_number?.trim() ||
    (!isAutoGeneratedPartNumber(part.part_number) ? part.part_number.trim() : '')
  const nextQty =
    updates.quantity != null && Number.isFinite(updates.quantity) && updates.quantity > 0
      ? updates.quantity
      : hasRealBom && existing && existing.quantity > 0
        ? Number(existing.quantity)
        : null

  if (!hasRealBom) {
    if (!realPn || nextQty == null) {
      return pendingBomItemId(part.id)
    }
    return ensureBomLineForPart(
      { ...part, part_number: realPn },
      modelName,
      vehicleModelId,
      updates.stationCode ?? part.common_station,
      { quantity: nextQty, part_number: realPn }
    )
  }

  const bomId = existing!.id
  const bomUpdate: BomItemUpdateInput = {}
  if (updates.stationCode !== undefined) {
    bomUpdate.station_code_text = normalizeBomStationCodeText(updates.stationCode) || null
    bomUpdate.station_id = updates.stationId ?? null
    bomUpdate.needs_review = false
  }
  if (nextQty != null && updates.quantity != null) {
    bomUpdate.quantity = nextQty
    bomUpdate.qty_by_model_raw = `${modelName}=${nextQty}`
  }
  if (realPn && updates.part_number != null) {
    bomUpdate.part_number = realPn
  }

  if (Object.keys(bomUpdate).length > 0) {
    await updateBomItem(bomId, bomUpdate)
  }

  return bomId
}

function bomRowMatchesModel(
  row: Pick<BomItemDetail, 'vehicle_model_name' | 'applicable_models_text' | 'qty_by_model_raw' | 'quantity'>,
  modelName: string
): boolean {
  return bomRowAppliesToModel(row, modelName)
}

export function buildIplModelMergedRows(
  modelName: string,
  allBom: BomItemDetail[],
  masters: Part[],
  filters: { search?: string; stationCode?: string }
): BomItemDetail[] {
  const target = modelName.trim().toUpperCase()
  const bomByLine = new Map<string, BomItemDetail>()
  for (const row of allBom) {
    if (!bomRowAssignedToIplModel(row, modelName)) continue
    const station = (row.station_code_text ?? '').trim().toUpperCase() || '_'
    const lineKey = `${row.part_id}|${station}`
    const existing = bomByLine.get(lineKey)
    if (!existing) {
      bomByLine.set(lineKey, row)
      continue
    }
    if (row.vehicle_model_name?.trim().toUpperCase() === target) {
      bomByLine.set(lineKey, row)
    }
  }

  const bomRows = [...bomByLine.values()]
  const bomPartIds = new Set(bomRows.map(r => r.part_id))
  const mastersById = new Map(masters.map(p => [p.id, p]))
  const pending = masters.filter(p => isPartsListMaster(p) && !bomPartIds.has(p.id))

  let merged: BomItemDetail[] = [
    ...bomRows.map(row => {
      const master = mastersById.get(row.part_id)
      return master
        ? mergePartToBomItem(master, row, modelName)
        : { ...row, part_number: isAutoGeneratedPartNumber(row.part_number) ? '' : row.part_number }
    }),
    ...pending.map(p => mergePartToBomItem(p, undefined, modelName))
  ]

  const stationCode = filters.stationCode?.trim().toUpperCase()
  if (stationCode) {
    merged = merged.filter(r => (r.station_code_text ?? '').trim().toUpperCase() === stationCode)
  }

  const search = filters.search?.trim().toLowerCase()
  if (search) {
    merged = merged.filter(r => {
      const hay = [r.part_name_ar, r.part_name_en, r.part_name, r.part_number].filter(Boolean).join(' ').toLowerCase()
      return hay.includes(search)
    })
  }

  merged.sort((a, b) => {
    const sa = (a.station_code_text ?? '').localeCompare(b.station_code_text ?? '', undefined, { numeric: true })
    if (sa !== 0) return sa
    return (a.part_name_ar ?? a.part_name ?? '').localeCompare(b.part_name_ar ?? b.part_name ?? '', 'ar')
  })

  return merged
}

export async function fetchIplBomAndMasters(search?: string): Promise<{ allBom: BomItemDetail[]; masters: Part[] }> {
  const [bomRes, masters] = await Promise.all([
    client().from('v_bom_items_detail').select('*').eq('is_active', true).limit(8000),
    listPartMastersLite({ search })
  ])
  if (bomRes.error) throw new Error(bomRes.error.message)
  return { allBom: (bomRes.data ?? []) as BomItemDetail[], masters }
}

export async function listIplModelViewRows(filters: {
  modelName: string
  search?: string
  stationCode?: string
  page?: number
  pageSize?: number
}): Promise<{ items: BomItemDetail[]; total: number }> {
  const modelName = filters.modelName.trim()
  if (!modelName) return { items: [], total: 0 }

  const page = filters.page ?? 1
  const pageSize = filters.pageSize ?? 100
  const { allBom, masters } = await fetchIplBomAndMasters(filters.search)
  const merged = buildIplModelMergedRows(modelName, allBom, masters, filters)
  const total = merged.length
  const from = (page - 1) * pageSize
  return { items: merged.slice(from, from + pageSize), total }
}

/** One shared fetch for compare mode — avoids N× full BOM/parts loads. */
export async function listIplModelViewsByModels(
  modelNames: string[],
  filters: { search?: string; stationCode?: string } = {}
): Promise<Map<string, BomItemDetail[]>> {
  const names = [...new Set(modelNames.map(n => n.trim()).filter(Boolean))]
  const result = new Map<string, BomItemDetail[]>()
  if (names.length === 0) return result

  const { allBom, masters } = await fetchIplBomAndMasters(filters.search)
  for (const modelName of names) {
    result.set(modelName, buildIplModelMergedRows(modelName, allBom, masters, filters))
  }
  return result
}

async function appendApplicableModel(
  partId: string,
  modelName: string,
  currentText: string | null | undefined
): Promise<void> {
  const names = parseApplicableModelNames(currentText ?? '')
  const target = modelName.trim()
  if (!target) return
  if (names.some(n => n.trim().toUpperCase() === target.toUpperCase())) return
  const next = [...names, target].join(', ')
  const { error } = await client().from('parts').update({ applicable_models_text: next }).eq('id', partId)
  if (error) throw new Error(error.message)
}

export async function ensureBomLineForPart(
  part: Pick<
    Part,
    'id' | 'part_number' | 'normalized_part_number' | 'part_name_ar' | 'part_name_en' | 'common_station'
  > & { applicable_models_text?: string | null },
  modelName: string,
  vehicleModelId: string,
  stationCode?: string | null,
  opts?: { quantity?: number; part_number?: string }
): Promise<string> {
  const existing = await getBomItemsForPartIds([part.id], modelName)
  const row = existing.get(part.id)
  if (row?.id && !isPendingBomItemId(row.id)) return row.id

  const pn = (opts?.part_number ?? part.part_number).trim()
  if (!pn || isAutoGeneratedPartNumber(pn)) {
    throw new Error('Part number is required')
  }
  const qty = opts?.quantity != null && Number.isFinite(opts.quantity) && opts.quantity > 0 ? opts.quantity : null
  if (qty == null) {
    throw new Error('Quantity is required')
  }

  const station = normalizeBomStationCodeText(stationCode ?? part.common_station ?? '')
  const norm = normalizePartNumber(pn)
  const lineKey = bomImportLineKey({
    normalizedPart: norm,
    stationCode: station || '_',
    modelName
  })

  const payload = {
    part_id: part.id,
    part_number: pn,
    part_name: part.part_name_ar?.trim() || part.part_name_en?.trim() || null,
    quantity: qty,
    vehicle_model_id: vehicleModelId,
    station_code_text: station || null,
    applicable_models_text: modelName,
    qty_by_model_raw: `${modelName}=${qty}`,
    import_line_key: lineKey,
    needs_review: !station,
    source_sheet: 'ipl_model',
    is_active: true,
    stopper_type: 'non_stopper' as const
  }

  const { data: dups } = await client().from('bom_items').select('id').eq('import_line_key', lineKey).limit(1)
  const dup = dups?.[0]
  if (dup?.id) {
    const { error } = await client()
      .from('bom_items')
      .update({ ...payload, is_active: true })
      .eq('id', dup.id)
    if (error) throw new Error(error.message)
    await appendApplicableModel(part.id, modelName, part.applicable_models_text)
    return dup.id as string
  }

  const { data, error } = await client().from('bom_items').insert(payload).select('id').single()
  if (error) {
    const { data: again } = await client().from('bom_items').select('id').eq('import_line_key', lineKey).limit(1)
    const existing = again?.[0]
    if (existing?.id) {
      const { error: updErr } = await client()
        .from('bom_items')
        .update({ ...payload, is_active: true })
        .eq('id', existing.id)
      if (updErr) throw new Error(updErr.message)
      await appendApplicableModel(part.id, modelName, part.applicable_models_text)
      return existing.id as string
    }
    throw new Error(error.message)
  }
  await appendApplicableModel(part.id, modelName, part.applicable_models_text)
  return data.id as string
}

export async function ensureIplNotFittedLine(
  part: Pick<Part, 'id' | 'part_number'>,
  modelName: string,
  vehicleModelId: string
): Promise<string> {
  const lineKey = bomImportLineKey({
    normalizedPart: `NF-${part.id}`,
    stationCode: '_',
    modelName
  })
  const payload = {
    part_id: part.id,
    part_number: IPL_NOT_FITTED_PN,
    part_name: null as string | null,
    quantity: 0,
    vehicle_model_id: vehicleModelId,
    station_code_text: null as string | null,
    applicable_models_text: modelName,
    qty_by_model_raw: `${modelName}=${IPL_NOT_FITTED_QTY}`,
    import_line_key: lineKey,
    needs_review: false,
    source_sheet: IPL_NOT_FITTED_SHEET,
    is_active: true,
    stopper_type: 'non_stopper' as const
  }

  const { data: nfDups } = await client().from('bom_items').select('id').eq('import_line_key', lineKey).limit(1)
  const dup = nfDups?.[0]
  if (dup?.id) {
    const { error } = await client()
      .from('bom_items')
      .update({ ...payload, is_active: true })
      .eq('id', dup.id)
    if (error) throw new Error(error.message)
    return dup.id as string
  }

  const { data, error } = await client().from('bom_items').insert(payload).select('id').single()
  if (error) throw new Error(error.message)
  return data.id as string
}

export async function updateBomItemStationForPart(
  part: Pick<
    Part,
    'id' | 'part_number' | 'normalized_part_number' | 'part_name_ar' | 'part_name_en' | 'common_station'
  >,
  modelName: string,
  vehicleModelId: string,
  stationCode: string,
  stationId?: string | null
): Promise<string> {
  const existing = await getBomItemsForPartIds([part.id], modelName)
  const row = existing.get(part.id)
  if (row?.id && !isPendingBomItemId(row.id)) {
    await updateBomItem(row.id, {
      station_code_text: normalizeBomStationCodeText(stationCode) || null,
      station_id: stationId ?? null,
      needs_review: false
    })
    return row.id
  }

  const { error } = await client()
    .from('parts')
    .update({ common_station: normalizeBomStationCodeText(stationCode) || null })
    .eq('id', part.id)
  if (error) throw new Error(error.message)
  return pendingBomItemId(part.id)
}

export async function deactivateBomItemsForPartModel(partId: string, modelName: string): Promise<void> {
  const map = await getBomItemsForPartIds([partId], modelName)
  const row = map.get(partId)
  if (row?.id && !isPendingBomItemId(row.id)) {
    await deleteBomItem(row.id)
  }
}

export async function deactivateAllBomItemsForPart(partId: string): Promise<void> {
  const { data, error } = await client()
    .from('bom_items')
    .select('id')
    .eq('part_id', partId)
    .eq('is_active', true)
  if (error) throw new Error(error.message)
  for (const row of data ?? []) {
    await deleteBomItem(row.id as string)
  }
}
