import { supabase } from '../lib/supabase'
import type { Part, BomItemDetail, PartListRow } from '../Types/bom'
import { parseApplicableModelNames, partMasterModelCount } from '../Utils/bomQtyByModel'
import { partMatchesIplModel } from '../Utils/iplModelParts'
import { displayBomStationCode } from '../Utils/bomStationCode'
import { normalizePartNumber } from '../Utils/partNumberNormalize'
import { effectivePartKind, effectiveSupplySource, DEFAULT_PART_KIND, DEFAULT_SUPPLY_SOURCE } from '../Utils/bomDefaults'
import { dedupePartListRows, partListMasterKey, pickBestPartMaster, scorePartMasterRow } from '../Utils/partListMaster'

export { isAutoGeneratedPartNumber } from '../Utils/iplModelParts'

function client() {
  if (!supabase) throw new Error('Supabase is not configured')
  return supabase
}

export async function getPartById(id: string): Promise<Part | null> {
  const { data, error } = await client().from('parts').select('*').eq('id', id).maybeSingle()
  if (error) throw new Error(error.message)
  return data as Part | null
}

export async function updatePartCategory(partId: string, categoryId: string | null): Promise<void> {
  const { error } = await client().from('parts').update({ category_id: categoryId }).eq('id', partId)
  if (error) throw new Error(error.message)
}

export async function updatePartNames(
  partId: string,
  names: {
    part_name_ar?: string | null
    part_name_en?: string | null
    common_station?: string | null
    common_name?: string | null
  }
): Promise<void> {
  const { error } = await client()
    .from('parts')
    .update({
      part_name_ar: names.part_name_ar?.trim() || null,
      part_name_en: names.part_name_en?.trim() || null,
      common_station: names.common_station?.trim() || null,
      common_name: names.common_name?.trim() || null
    })
    .eq('id', partId)
  if (error) throw new Error(error.message)
}

export type PartMasterInput = {
  common_station?: string | null
  part_name_ar?: string | null
  part_name_en?: string | null
  common_name?: string | null
  part_type?: string | null
  common_supply_source?: string | null
  /** Used from IPL models tab when removing/assigning models on a part */
  model_names?: string[]
}

function formatApplicableModelsText(names: string[]): string | null {
  const clean = [...new Set(names.map(n => n.trim()).filter(Boolean))]
  return clean.length ? clean.join(', ') : null
}

function buildPartMasterPayload(input: PartMasterInput): Record<string, string | null> {
  const payload: Record<string, string | null> = {
    part_name_ar: trimOrNull(input.part_name_ar),
    part_name_en: trimOrNull(input.part_name_en),
    common_station: trimOrNull(input.common_station),
    common_name: trimOrNull(input.common_name),
    part_type: masterPartType(input),
    common_supply_source: masterSupplySource(input)
  }
  if (input.model_names !== undefined) {
    payload.applicable_models_text = formatApplicableModelsText(input.model_names)
  }
  return payload
}

function trimOrNull(v?: string | null): string | null {
  const s = v?.trim()
  return s || null
}

function masterPartType(input: PartMasterInput): string {
  return effectivePartKind(input.part_type ?? DEFAULT_PART_KIND)
}

function masterSupplySource(input: PartMasterInput): string {
  return effectiveSupplySource(input.common_supply_source ?? DEFAULT_SUPPLY_SOURCE)
}

function partNumberSeed(input: PartMasterInput): string {
  return (
    trimOrNull(input.common_name) ||
    trimOrNull(input.part_name_en) ||
    trimOrNull(input.part_name_ar) ||
    trimOrNull(input.common_station) ||
    ''
  )
}

function generatedPartNumber(seed: string): string {
  const base = normalizePartNumber(seed, { ignoreDashes: false }).replace(/[^A-Z0-9-]/g, '')
  const suffix = Date.now().toString(36).toUpperCase()
  return (base ? base.slice(0, 32) : 'PART') + '-' + suffix
}

export async function createPartMaster(input: PartMasterInput): Promise<{ id: string }> {
  const existing = await findExistingPartMaster(input)
  if (existing) {
    await updatePartMaster(existing.id, {
      ...input,
      common_name: input.common_name?.trim() || existing.common_name || input.part_name_ar
    })
    return { id: existing.id }
  }

  const partNumber = generatedPartNumber(partNumberSeed(input) || 'PART')

  const { data, error } = await client()
    .from('parts')
    .insert({
      part_number: partNumber,
      normalized_part_number: normalizePartNumber(partNumber),
      ...buildPartMasterPayload(input)
    })
    .select('id')
    .single()

  if (error) throw new Error(error.message)
  return { id: data.id as string }
}

export async function updatePartMaster(partId: string, input: PartMasterInput): Promise<void> {
  const { error } = await client()
    .from('parts')
    .update(buildPartMasterPayload(input))
    .eq('id', partId)

  if (error) throw new Error(error.message)
}

export async function deletePart(partId: string): Promise<void> {
  const { error } = await client().from('parts').update({ is_active: false }).eq('id', partId)
  if (error) throw new Error(error.message)
}

async function findExistingPartMaster(input: PartMasterInput): Promise<Part | null> {
  const ar = input.part_name_ar?.trim()
  if (!ar) return null
  const { data, error } = await client()
    .from('parts')
    .select('*')
    .eq('is_active', true)
    .ilike('part_name_ar', ar)
    .limit(20)
  if (error) throw new Error(error.message)
  const target = ar.toLowerCase()
  const matches = ((data ?? []) as Part[]).filter(p => p.part_name_ar?.trim().toLowerCase() === target)
  return matches.length ? pickBestPartMaster(matches) : null
}

function partToMasterHit(part: Part): PartMasterHit {
  return {
    id: part.id,
    part_number: part.part_number,
    part_name_ar: part.part_name_ar,
    part_name_en: part.part_name_en,
    common_name: part.common_name,
    common_station: part.common_station,
    part_type: part.part_type,
    common_supply_source: part.common_supply_source
  }
}

/** Exact Arabic name match in parts master list (optionally excluding one id). */
export async function findPartMasterByArabicName(
  name: string,
  excludeId?: string | null
): Promise<PartMasterHit | null> {
  const existing = await findExistingPartMaster({ part_name_ar: name })
  if (!existing) return null
  if (excludeId && existing.id === excludeId) return null
  return partToMasterHit(existing)
}

/** Merge duplicate master-list rows that share the same Arabic name. */
export async function consolidateDuplicatePartMasters(): Promise<number> {
  const { data, error } = await client().from('parts').select('*').eq('is_active', true).limit(5000)
  if (error) throw new Error(error.message)

  const groups = new Map<string, Part[]>()
  for (const part of (data ?? []) as Part[]) {
    const key = partListMasterKey(part)
    if (key.startsWith('id:')) continue
    const bucket = groups.get(key) ?? []
    bucket.push(part)
    groups.set(key, bucket)
  }

  let removed = 0
  for (const group of groups.values()) {
    if (group.length <= 1) continue
    const canonical = pickBestPartMaster(group)
    for (const dup of group) {
      if (dup.id === canonical.id) continue
      const { error: bomErr } = await client().from('bom_items').update({ part_id: canonical.id }).eq('part_id', dup.id)
      if (bomErr) throw new Error(bomErr.message)
      await deletePart(dup.id)
      removed++
    }
  }
  return removed
}

export type PartListStationOption = {
  code: string
  label: string
}

export type PartsListFilters = {
  search?: string
  modelName?: string
  stationCode?: string
  page?: number
  pageSize?: number
}

export async function listPartsForIplModel(
  filters: PartsListFilters & { modelName: string }
): Promise<{ items: PartListRow[]; total: number }> {
  const modelName = filters.modelName.trim()
  if (!modelName) return { items: [], total: 0 }

  const page = filters.page ?? 1
  const pageSize = filters.pageSize ?? 100

  let q = client()
    .from('parts')
    .select('*')
    .eq('is_active', true)
    .order('common_station', { ascending: true, nullsFirst: false })
    .order('common_name', { ascending: true, nullsFirst: false })
    .order('part_name_ar', { ascending: true })
    .limit(5000)

  const search = filters.search?.trim()
  if (search) {
    const s = search.replace(/%/g, '\\%')
    q = q.or(
      `common_station.ilike.%${s}%,common_name.ilike.%${s}%,part_name_ar.ilike.%${s}%,part_name_en.ilike.%${s}%,part_number.ilike.%${s}%`
    )
  }

  const { data, error } = await q
  if (error) throw new Error(error.message)

  let parts = dedupePartListRows(((data ?? []) as Part[]).filter(p => partMatchesIplModel(p, modelName)))

  const stationCode = filters.stationCode?.trim()
  if (stationCode) {
    const code = stationCode.toUpperCase()
    parts = parts.filter(p => (p.common_station ?? '').trim().toUpperCase() === code)
  }

  const total = parts.length
  const from = (page - 1) * pageSize
  const pageItems = parts.slice(from, from + pageSize).map(p => ({ ...p }))

  return { items: pageItems, total }
}

export type PartMasterHit = {
  id: string
  part_number: string
  part_name_ar: string | null
  part_name_en: string | null
  common_name: string | null
  common_station: string | null
  part_type: string | null
  common_supply_source: string | null
}

export async function searchPartsMaster(term: string, limit = 15): Promise<PartMasterHit[]> {
  const q = term.trim().replace(/%/g, '\\%')
  if (!q) return []

  const { data, error } = await client()
    .from('parts')
    .select(
      'id, part_number, part_name_ar, part_name_en, common_name, common_station, part_type, common_supply_source'
    )
    .eq('is_active', true)
    .or(
      `part_name_ar.ilike.%${q}%,part_name_en.ilike.%${q}%,common_name.ilike.%${q}%,common_station.ilike.%${q}%`
    )
    .order('common_name', { ascending: true, nullsFirst: false })
    .order('part_name_ar', { ascending: true })
    .limit(limit)

  if (error) throw new Error(error.message)
  const hits = (data ?? []) as PartMasterHit[]
  const byKey = new Map<string, PartMasterHit>()
  for (const hit of hits) {
    const key = partListMasterKey({
      id: hit.id,
      part_name_ar: hit.part_name_ar,
      part_name_en: hit.part_name_en,
      common_name: hit.common_name
    })
    const prev = byKey.get(key)
    if (!prev || scorePartMasterRow(hit as Part) > scorePartMasterRow(prev as Part)) {
      byKey.set(key, hit)
    }
  }
  return [...byKey.values()]
}

async function countModelsByPartIds(partIds: string[]): Promise<Map<string, Array<{
  qty_by_model_raw: string | null
  applicable_models_text: string | null
  vehicle_model_name: string | null
  quantity: number | null
}>>> {
  const rowsByPart = new Map<string, Array<{
    qty_by_model_raw: string | null
    applicable_models_text: string | null
    vehicle_model_name: string | null
    quantity: number | null
  }>>()
  if (partIds.length === 0) return rowsByPart

  const CHUNK = 100
  for (let i = 0; i < partIds.length; i += CHUNK) {
    const chunk = partIds.slice(i, i + CHUNK)
    const { data, error } = await client()
      .from('v_bom_items_detail')
      .select('part_id, qty_by_model_raw, applicable_models_text, vehicle_model_name, quantity')
      .eq('is_active', true)
      .in('part_id', chunk)
    if (error) throw new Error(error.message)
    for (const row of data ?? []) {
      const pid = row.part_id as string
      const bucket = rowsByPart.get(pid) ?? []
      bucket.push({
        qty_by_model_raw: row.qty_by_model_raw as string | null,
        applicable_models_text: row.applicable_models_text as string | null,
        vehicle_model_name: row.vehicle_model_name as string | null,
        quantity: row.quantity as number | null
      })
      rowsByPart.set(pid, bucket)
    }
  }
  return rowsByPart
}

export async function listParts(filters: PartsListFilters = {}): Promise<{ items: PartListRow[]; total: number }> {
  await consolidateDuplicatePartMasters().catch(() => 0)

  const page = filters.page ?? 1
  const pageSize = filters.pageSize ?? 80

  const deduped = await listPartMastersLite({ search: filters.search })
  const from = (page - 1) * pageSize
  const pageItems = deduped.slice(from, from + pageSize)
  const bomByPart = await countModelsByPartIds(pageItems.map(p => p.id))
  const items: PartListRow[] = pageItems.map(p => ({
    ...p,
    model_count: partMasterModelCount(p, bomByPart.get(p.id) ?? [])
  }))
  return {
    items,
    total: deduped.length
  }
}

/** Lightweight masters for IPL views — no consolidate / model_count (avoids N× heavy loads). */
export async function listPartMastersLite(filters: { search?: string } = {}): Promise<Part[]> {
  let q = client()
    .from('parts')
    .select('*')
    .eq('is_active', true)
    .order('common_station', { ascending: true, nullsFirst: false })
    .order('common_name', { ascending: true, nullsFirst: false })
    .order('part_name_ar', { ascending: true })
    .limit(5000)

  const search = filters.search?.trim()
  if (search) {
    const esc = search.replace(/%/g, '\\%')
    q = q.or(
      `common_station.ilike.%${esc}%,common_name.ilike.%${esc}%,part_name_ar.ilike.%${esc}%,part_name_en.ilike.%${esc}%,part_number.ilike.%${esc}%`
    )
  }

  const { data, error } = await q
  if (error) throw new Error(error.message)
  return dedupePartListRows((data ?? []) as Part[])
}

export async function getPartBomUsage(partId: string): Promise<BomItemDetail[]> {
  const { data, error } = await client()
    .from('v_bom_items_detail')
    .select('*')
    .eq('part_id', partId)
    .order('station_code_text')
    .limit(500)
  if (error) throw new Error(error.message)
  return (data ?? []) as BomItemDetail[]
}

export type PartUpsertInput = {
  part_number: string
  part_name_ar?: string
  part_name_en?: string
  category_id?: string | null
  part_type?: string
  part_number_new?: string
  alternative_part_no?: string
}

export async function upsertPart(input: PartUpsertInput): Promise<{ id: string; created: boolean }> {
  const normalized = normalizePartNumber(input.part_number)
  const { data: existing } = await client()
    .from('parts')
    .select('id')
    .eq('normalized_part_number', normalized)
    .maybeSingle()

  const payload = {
    part_number: input.part_number.trim(),
    normalized_part_number: normalized,
    part_name_ar: input.part_name_ar?.trim() || null,
    part_name_en: input.part_name_en?.trim() || null,
    category_id: input.category_id ?? null,
    part_type: input.part_type?.trim() || null,
    part_number_new: input.part_number_new?.trim() || null,
    alternative_part_no: input.alternative_part_no?.trim() || null
  }

  if (existing?.id) {
    const { error } = await client().from('parts').update(payload).eq('id', existing.id)
    if (error) throw new Error(error.message)
    return { id: existing.id as string, created: false }
  }

  const { data, error } = await client().from('parts').insert(payload).select('id').single()
  if (error) throw new Error(error.message)
  return { id: data.id as string, created: true }
}

export async function getT4cIplStationOptions(): Promise<PartListStationOption[]> {
  const { data: stations, error: stErr } = await client()
    .from('stations')
    .select('station_number, station_name, sort_order')
    .eq('is_active', true)
    .order('sort_order')

  if (stErr) throw new Error(stErr.message)

  type StationOpt = { code: string; label: string; sort: number }
  const options = new Map<string, StationOpt>()

  for (const s of stations ?? []) {
    const code = displayBomStationCode(String(s.station_number ?? ''))
    if (!code) continue
    const key = code.toUpperCase()
    options.set(key, {
      code,
      label: s.station_name ? `${code} — ${s.station_name}` : code,
      sort: Number(s.sort_order) || parseInt(code.replace(/\D/g, ''), 10) || 0
    })
  }

  const { data: models, error: modelErr } = await client()
    .from('vehicle_models')
    .select('id, name')
    .eq('is_active', true)

  if (modelErr) throw new Error(modelErr.message)

  const t4c = (models ?? []).find(m => {
    const name = String(m.name ?? '')
      .trim()
      .toUpperCase()
      .replace(/\s+/g, '')
    return name === 'T4C'
  })

  if (t4c?.id) {
    const { data: rows, error } = await client()
      .from('bom_items')
      .select('station_code_text, vehicle_model_id, applicable_models_text')
      .eq('is_active', true)
      .not('station_code_text', 'is', null)

    if (error) throw new Error(error.message)

    for (const row of rows ?? []) {
      const applies =
        row.vehicle_model_id === t4c.id ||
        String(row.applicable_models_text ?? '')
          .toUpperCase()
          .includes('T4C') ||
        parseApplicableModelNames(row.applicable_models_text).some(
          n => n.trim().toUpperCase().replace(/\s+/g, '') === 'T4C'
        )
      if (!applies) continue

      const code = displayBomStationCode(String(row.station_code_text ?? ''))
      if (!code) continue
      const key = code.toUpperCase()
      if (!options.has(key)) {
        options.set(key, {
          code,
          label: code,
          sort: parseInt(code.replace(/\D/g, ''), 10) || 9999
        })
      }
    }
  }

  return [...options.values()]
    .sort((a, b) => a.sort - b.sort || a.code.localeCompare(b.code, undefined, { numeric: true }))
    .map(({ code, label }) => ({ code, label }))
}
