import { useCallback, useEffect, useMemo, useRef, useState, startTransition } from 'react'
import { useLang } from '../i18n/LanguageContext'
import { usePermissions } from '../Context/PermissionsContext'
import { useAuth } from '../Context/AuthContext'
import { getVehicleModels, getStations } from '../services/settingsService'
import {
  deleteBomItem,
  getBomItemById,
  getBomItemsAll,
  type BomExcelColumnFilters,
  type BomListFilters
} from '../services/bomCrudService'
import {
  deactivateAllBomItemsForPart,
  deactivateBomItemsForPartModel,
  fetchIplBomAndMasters,
  buildIplModelMergedRows,
  updateBomIplFeedingCard,
  updateBomItemStationForPart,
  updateIplModelLine
} from '../services/bomIplService'
import {
  saveBomFromModelCards,
  savePartMasterFromListForm
} from '../services/bomPartMasterService'
import {
  deletePart,
  getPartById,
  getT4cIplStationOptions,
  isAutoGeneratedPartNumber,
  updatePartMaster,
  type PartListStationOption
} from '../services/partsService'
import { applicableModelsAfterRemoval } from '../Utils/bomQtyByModel'
import { isIplNotFittedForModel } from '../Utils/iplFitStatus'
import { isPendingBomItemId } from '../Utils/iplModelParts'
import {
  BOM_IPL_MODEL_ROW_COLUMNS,
  BOM_IPL_TABLE_COL_WIDTH,
  BOM_MAIN_ROW_COLUMNS,
  BOM_TABLE_COL_WIDTH
} from '../Utils/bomPartsColumns'
import { groupBomItemsForDisplay, bomItemsAsFlatGroups, type BomDisplayGroup } from '../Utils/bomRowGroups'
import {
  bomRowsByModelName,
  buildBreakdownSaveCards,
  cardsCanConsolidate,
  familyIdForModel
} from '../Utils/bomModelCards'
import type { BomModelLineDraft } from '../Utils/bomModelBreakdown'
import { effectiveBomStopperType } from '../Utils/bomStopper'
import {
  buildModelFamilyGroups,
  isSelectableVehicleModel,
  selectableVehicleModels
} from '../Utils/vehicleModelHierarchy'
import { filterBomItemsByLineScope, filterModelFamilyPicker, isGdModelName, type BomLineScope } from '../Utils/bomModelScope'
import { preferredIplModelName } from '../Utils/iplModelAliases'
import { masterStationsForBom, normalizeBomStationCodeText, sortBomDisplayGroups } from '../Utils/bomStationCode'
import type { BomFilterColumn } from '../Utils/bomFilterFields'
import { DEFAULT_PART_KIND, DEFAULT_SUPPLY_SOURCE } from '../Utils/bomDefaults'
import type { PartListFormState, PartListSavePayload } from '../Components/bom/BomPartListFormModal'
import type { BomItemDetail, Part } from '../Types/bom'
import type { BomIplFeedingCard } from '../Utils/iplBomLogistics'
import type { VehicleModel, Station } from '../Types/settings'

const PAGE_SIZE = 100

const emptyPartForm = (): PartListFormState => ({
  common_station: '',
  part_name_ar: '',
  part_name_en: '',
  common_name: '',
  part_type: DEFAULT_PART_KIND,
  common_supply_source: DEFAULT_SUPPLY_SOURCE
})

export function useBomByModelData({
  notify,
  lineScope = 'main',
  viewMode = 'consolidated'
}: {
  notify: (m: string, err?: boolean) => void
  lineScope?: BomLineScope
  viewMode?: 'consolidated' | 'perModel'
}) {
  const { t } = useLang()
  const { hasRole } = useAuth()
  const { hasPermission } = usePermissions()
  const canCreate = hasRole('admin') || hasPermission('bom', 'create')
  const canUpdate = hasRole('admin') || hasPermission('bom', 'update')
  const canDelete = hasRole('admin') || hasPermission('bom', 'delete') || canUpdate

  const [models, setModels] = useState<VehicleModel[]>([])
  const [stations, setStations] = useState<Station[]>([])
  const [modelName, setModelName] = useState('')
  const [openModelTabs, setOpenModelTabs] = useState<string[]>([])
  const [activeModelTab, setActiveModelTab] = useState('')
  const [compareItemsByModel, setCompareItemsByModel] = useState<Map<string, BomItemDetail[]>>(new Map())
  const [stationId, setStationId] = useState('')
  const [search, setSearch] = useState('')
  const [searchDebounced, setSearchDebounced] = useState('')
  const [stopperType, setStopperType] = useState('')
  const [noOperationOnly, setNoOperationOnly] = useState(false)
  const [excelFilters, setExcelFilters] = useState<BomExcelColumnFilters>({})
  const [page, setPage] = useState(1)
  const [items, setItems] = useState<BomItemDetail[]>([])
  const [total, setTotal] = useState(0)
  const [filteredCount, setFilteredCount] = useState<number | null>(null)
  const [loading, setLoading] = useState(false)
  const [formMode, setFormMode] = useState<'create' | 'edit' | null>(null)
  const [editId, setEditId] = useState<string | null>(null)
  const [editIds, setEditIds] = useState<string[]>([])
  const [deleteTarget, setDeleteTarget] = useState<{
    group: BomDisplayGroup
    variant?: { id: string; modelName: string }
  } | null>(null)
  const [deleting, setDeleting] = useState(false)
  const [breakdownSaving, setBreakdownSaving] = useState(false)
  const [iplSaving, setIplSaving] = useState(false)
  const [expandedKeys, setExpandedKeys] = useState<Set<string>>(new Set())
  const [stationOptions, setStationOptions] = useState<PartListStationOption[]>([])
  const [partFormOpen, setPartFormOpen] = useState(false)
  const [partEditId, setPartEditId] = useState<string | null>(null)
  const [partForm, setPartForm] = useState<PartListFormState>(emptyPartForm)
  const [partFormBusy, setPartFormBusy] = useState(false)
  const [iplLogisticsGroup, setIplLogisticsGroup] = useState<BomDisplayGroup | null>(null)
  const [iplDeleteTarget, setIplDeleteTarget] = useState<BomDisplayGroup | null>(null)
  const [partsCache, setPartsCache] = useState<Map<string, Part>>(new Map())
  const didInitModelTabs = useRef(false)
  const loadSeq = useRef(0)
  const iplSourceRef = useRef<{ allBom: BomItemDetail[]; masters: Part[] } | null>(null)
  const iplPaintedRef = useRef(false)
  const [iplRefreshing, setIplRefreshing] = useState(false)

  const perModel = viewMode === 'perModel'
  const effectiveModelName = perModel ? activeModelTab : modelName
  const modelPicker = useMemo(
    () => filterModelFamilyPicker(buildModelFamilyGroups(models), lineScope),
    [models, lineScope]
  )
  const masterStations = useMemo(() => masterStationsForBom(stations), [stations])
  const assignableModels = useMemo(() => {
    const all = selectableVehicleModels(models)
    if (lineScope === 'gd') return all.filter(m => isGdModelName(m.name))
    return all.filter(m => !isGdModelName(m.name))
  }, [models, lineScope])
  const assignableModelNames = useMemo(() => new Set(assignableModels.map(m => m.name)), [assignableModels])
  const openTabsActive = useMemo(
    () => openModelTabs.filter(name => assignableModelNames.has(name)),
    [openModelTabs, assignableModelNames]
  )
  const openTabsKey = openTabsActive.join('\u0001')
  const compareMode = perModel && openTabsActive.length > 1
  const stationCodeForLoad = useMemo(() => {
    if (!stationId) return undefined
    const st = masterStations.find(s => s.id === stationId)
    return st ? normalizeBomStationCodeText(st.station_number) : undefined
  }, [stationId, masterStations])
  const scopedItems = useMemo(() => filterBomItemsByLineScope(items, lineScope), [items, lineScope])
  const displayGroups = useMemo(
    () =>
      sortBomDisplayGroups(
        perModel ? bomItemsAsFlatGroups(scopedItems) : groupBomItemsForDisplay(scopedItems),
        stations
      ),
    [scopedItems, stations, perModel]
  )
  const pagedGroups = useMemo(() => {
    const start = (page - 1) * PAGE_SIZE
    return displayGroups.slice(start, start + PAGE_SIZE)
  }, [displayGroups, page])
  const groupTotal = displayGroups.length

  const rowColumns = perModel ? BOM_IPL_MODEL_ROW_COLUMNS : BOM_MAIN_ROW_COLUMNS
  const colWidths = perModel ? BOM_IPL_TABLE_COL_WIDTH : BOM_TABLE_COL_WIDTH
  const colCount = rowColumns.length

  const baseFilters = useMemo((): Omit<BomListFilters, 'page' | 'pageSize'> => {
    const f: Omit<BomListFilters, 'page' | 'pageSize'> = { search: searchDebounced, excel: excelFilters }
    if (effectiveModelName) f.modelName = effectiveModelName
    if (stationId) {
      const st = masterStations.find(s => s.id === stationId)
      f.stationId = stationId
      if (st) f.stationNumber = normalizeBomStationCodeText(st.station_number)
    }
    if (stopperType) f.stopperType = stopperType as BomListFilters['stopperType']
    if (noOperationOnly) f.noOperationOnly = true
    return f
  }, [searchDebounced, effectiveModelName, stationId, masterStations, excelFilters, stopperType, noOperationOnly])

  const activeExcelFilterCount = Object.values(excelFilters).filter(v => v && v.length > 0).length

  useEffect(() => {
    const timer = window.setTimeout(() => setSearchDebounced(search.trim()), perModel ? 180 : 350)
    return () => window.clearTimeout(timer)
  }, [search, perModel])

  const applyIplFromSource = useCallback(
    (source: { allBom: BomItemDetail[]; masters: Part[] }) => {
      const filters = { search: searchDebounced, stationCode: stationCodeForLoad }
      if (compareMode) {
        const byModel = new Map<string, BomItemDetail[]>()
        for (const name of openTabsActive) {
          byModel.set(name, buildIplModelMergedRows(name, source.allBom, source.masters, filters))
        }
        const uniqueParts = new Set<string>()
        for (const rows of byModel.values()) {
          for (const row of rows) uniqueParts.add(row.part_id || row.id)
        }
        startTransition(() => {
          setCompareItemsByModel(byModel)
          setItems([])
          setTotal(uniqueParts.size)
          setFilteredCount(uniqueParts.size)
        })
        return
      }

      const merged = buildIplModelMergedRows(activeModelTab, source.allBom, source.masters, filters).filter(
        row => !isIplNotFittedForModel(row, activeModelTab)
      )
      const from = (page - 1) * PAGE_SIZE
      startTransition(() => {
        setCompareItemsByModel(new Map())
        setPartsCache(new Map())
        setItems(merged.slice(from, from + PAGE_SIZE))
        setTotal(merged.length)
        setFilteredCount(merged.length)
      })
    },
    [compareMode, openTabsActive, searchDebounced, stationCodeForLoad, activeModelTab, page]
  )

  const load = useCallback(async (opts?: { force?: boolean }) => {
    const seq = ++loadSeq.current
    if (perModel && openTabsActive.length === 0) {
      if (seq !== loadSeq.current) return
      setItems([])
      setTotal(0)
      setFilteredCount(0)
      setCompareItemsByModel(new Map())
      setLoading(false)
      setIplRefreshing(false)
      return
    }
    if (perModel && !compareMode && (!activeModelTab || !assignableModelNames.has(activeModelTab))) {
      if (seq !== loadSeq.current) return
      setLoading(false)
      setIplRefreshing(false)
      return
    }

    try {
      if (perModel) {
        const cached = !opts?.force ? iplSourceRef.current : null
        if (cached) {
          applyIplFromSource(cached)
          iplPaintedRef.current = true
          if (seq === loadSeq.current) {
            setLoading(false)
            setIplRefreshing(false)
          }
          return
        }

        if (iplPaintedRef.current) setIplRefreshing(true)
        else setLoading(true)

        const source = await fetchIplBomAndMasters()
        if (seq !== loadSeq.current) return
        iplSourceRef.current = source
        applyIplFromSource(source)
        iplPaintedRef.current = true
      } else {
        setLoading(true)
        const list = await getBomItemsAll(baseFilters)
        if (seq !== loadSeq.current) return
        setItems(list.items)
        setTotal(list.total)
        setFilteredCount(list.total)
        if (list.truncated) notify(t('bom.mergeTruncated'), true)
      }
    } catch (e) {
      if (seq !== loadSeq.current) return
      notify(e instanceof Error ? e.message : t('common.error'), true)
    } finally {
      if (seq === loadSeq.current) {
        setLoading(false)
        setIplRefreshing(false)
      }
    }
  }, [
    baseFilters,
    notify,
    t,
    perModel,
    activeModelTab,
    compareMode,
    assignableModelNames,
    openTabsActive,
    applyIplFromSource
  ])

  useEffect(() => {
    Promise.all([getVehicleModels(), getStations()])
      .then(([m, s]) => {
        setModels(m)
        setStations(s.filter(st => st.is_active))
      })
      .catch(() => notify(t('common.error'), true))
  }, [notify, t])

  useEffect(() => {
    if (!perModel) return
    setOpenModelTabs(prev => {
      const next = prev.filter(n => assignableModelNames.has(n))
      return next.length === prev.length && next.every((n, i) => n === prev[i]) ? prev : next
    })
    setActiveModelTab(prev => (assignableModelNames.has(prev) ? prev : assignableModels[0]?.name ?? ''))
  }, [perModel, assignableModels, assignableModelNames])

  useEffect(() => {
    if (!perModel) return
    const refreshModels = () => {
      void getVehicleModels()
        .then(setModels)
        .catch(() => {})
    }
    document.addEventListener('visibilitychange', refreshModels)
    return () => document.removeEventListener('visibilitychange', refreshModels)
  }, [perModel])

  useEffect(() => {
    if (!perModel || assignableModels.length === 0 || didInitModelTabs.current) return
    didInitModelTabs.current = true
    const allNames = assignableModels.map(m => m.name)
    const preferred = preferredIplModelName(allNames)
    setOpenModelTabs(preferred ? [preferred] : allNames.slice(0, 1))
    setActiveModelTab((preferred ?? allNames[0]) || '')
  }, [perModel, assignableModels])

  function toggleModelTab(name: string) {
    setOpenModelTabs(prev => {
      if (prev.includes(name)) {
        const next = prev.filter(n => n !== name)
        setActiveModelTab(cur => (cur === name ? next[0] ?? '' : cur))
        return next
      }
      setActiveModelTab(name)
      return [...prev, name].sort((a, b) => a.localeCompare(b))
    })
    setPage(1)
  }

  function toggleFamilyTabs(variantNames: string[]) {
    setOpenModelTabs(prev => {
      const allOn = variantNames.length > 0 && variantNames.every(n => prev.includes(n))
      const next = allOn
        ? prev.filter(n => !variantNames.includes(n))
        : [...new Set([...prev, ...variantNames])].sort((a, b) => a.localeCompare(b))
      setActiveModelTab(cur => (next.includes(cur) ? cur : next[0] ?? ''))
      return next
    })
    setPage(1)
  }

  useEffect(() => {
    if (!perModel) return
    void getT4cIplStationOptions()
      .then(setStationOptions)
      .catch(() => setStationOptions([]))
  }, [perModel])

  function reload(msg?: string) {
    iplSourceRef.current = null
    void load({ force: true }).then(() => {
      if (msg) notify(msg)
    })
  }

  function setColumnFilter(col: BomFilterColumn, values: string[] | undefined) {
    setExcelFilters(prev => {
      const next = { ...prev }
      if (!values) delete next[col]
      else next[col] = values
      return next
    })
    setPage(1)
  }

  function clearAllExcelFilters() {
    setExcelFilters({})
    setPage(1)
  }

  async function confirmDelete() {
    if (!deleteTarget) return
    setDeleting(true)
    try {
      if (deleteTarget.variant) {
        await deleteBomItem(deleteTarget.variant.id)
      } else {
        for (const id of deleteTarget.group.allIds) {
          await deleteBomItem(id)
        }
      }
      setDeleteTarget(null)
      reload(t('settings.deleted'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
    } finally {
      setDeleting(false)
    }
  }

  function toggleExpanded(key: string) {
    setExpandedKeys(prev => {
      const next = new Set(prev)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })
  }

  useEffect(() => {
    void load()
  }, [load])

  async function saveIplLogistics(itemIds: string[], card: BomIplFeedingCard) {
    setIplSaving(true)
    try {
      if (perModel && iplLogisticsGroup) {
        const primaryId = iplLogisticsGroup.primary.id
        if (isPendingBomItemId(primaryId)) {
          throw new Error(t('bom.iplNeedPartNumberAndQty'))
        }
        await updateBomIplFeedingCard([primaryId], card)
      } else {
        await updateBomIplFeedingCard(itemIds, card)
      }
      reload(t('settings.updated'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
      throw e
    } finally {
      setIplSaving(false)
    }
  }

  async function onIplFieldSave(group: BomDisplayGroup, field: 'part_number' | 'qty', value: string) {
    if (!canUpdate || !effectiveModelName) return
    const part = partsCache.get(group.primary.part_id) ?? (await getPartById(group.primary.part_id))
    const vehicleModel = models.find(m => m.name === effectiveModelName)
    if (!part || !vehicleModel) return
    try {
      if (field === 'part_number') {
        await updateIplModelLine(part, effectiveModelName, vehicleModel.id, { part_number: value })
      } else {
        const quantity = Number(value)
        if (!Number.isFinite(quantity) || quantity <= 0) return
        const fresh = (await getPartById(part.id)) ?? part
        if (isAutoGeneratedPartNumber(fresh.part_number)) {
          notify(t('bom.iplNeedPartNumberFirst'), true)
          return
        }
        await updateIplModelLine(fresh, effectiveModelName, vehicleModel.id, { quantity })
      }
      reload(t('settings.updated'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
    }
  }

  async function onIplStationChange(group: BomDisplayGroup, stationCode: string) {
    if (!canUpdate || !effectiveModelName) return
    const part = partsCache.get(group.primary.part_id) ?? (await getPartById(group.primary.part_id))
    const vehicleModel = models.find(m => m.name === effectiveModelName)
    if (!part || !vehicleModel) return
    const station = masterStations.find(s => normalizeBomStationCodeText(s.station_number) === stationCode)
    try {
      await updateBomItemStationForPart(part, effectiveModelName, vehicleModel.id, stationCode, station?.id ?? null)
      reload(t('settings.updated'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
    }
  }

  function openPartCreate() {
    setPartEditId(null)
    setPartForm(emptyPartForm())
    setPartFormOpen(true)
  }

  async function openPartEditById(partId: string) {
    const part = partsCache.get(partId) ?? (await getPartById(partId))
    if (!part) return
    setPartEditId(part.id)
    setPartForm({
      common_station: part.common_station ?? '',
      part_name_ar: part.part_name_ar ?? '',
      part_name_en: part.part_name_en ?? '',
      common_name: part.common_name ?? part.part_name_ar ?? part.part_name_en ?? '',
      part_type: part.part_type ?? DEFAULT_PART_KIND,
      common_supply_source: part.common_supply_source ?? DEFAULT_SUPPLY_SOURCE
    })
    setPartFormOpen(true)
  }

  async function openPartEdit(group: BomDisplayGroup) {
    await openPartEditById(group.primary.part_id)
  }

  async function submitPartForm(payload: PartListSavePayload) {
    setPartFormBusy(true)
    try {
      await savePartMasterFromListForm(
        payload.existingPartId ?? partEditId,
        {
          common_station: partForm.common_station,
          part_name_ar: partForm.part_name_ar,
          part_name_en: partForm.part_name_en,
          common_name: partForm.common_name,
          part_type: partForm.part_type,
          common_supply_source: partForm.common_supply_source
        },
        payload.cards,
        payload.models
      )
      setPartFormOpen(false)
      reload(payload.existingPartId || partEditId ? t('settings.updated') : t('settings.added'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
      throw e
    } finally {
      setPartFormBusy(false)
    }
  }

  async function confirmIplDelete() {
    if (!iplDeleteTarget || !effectiveModelName) return
    setDeleting(true)
    try {
      const partId = iplDeleteTarget.primary.part_id
      const part = partsCache.get(partId) ?? (await getPartById(partId))
      if (part && isAutoGeneratedPartNumber(part.part_number)) {
        await deactivateAllBomItemsForPart(partId)
        await deletePart(partId)
      } else if (part) {
        const next = applicableModelsAfterRemoval(
          part.applicable_models_text,
          effectiveModelName,
          assignableModels.map(m => m.name)
        )
        await updatePartMaster(partId, {
          common_station: part.common_station,
          part_name_ar: part.part_name_ar,
          part_name_en: part.part_name_en,
          common_name: part.common_name,
          model_names: next
        })
        await deactivateBomItemsForPartModel(partId, effectiveModelName)
      } else {
        await deactivateBomItemsForPartModel(partId, effectiveModelName)
      }
      setIplDeleteTarget(null)
      reload(t('settings.deleted'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
    } finally {
      setDeleting(false)
    }
  }

  async function saveBreakdown(group: BomDisplayGroup, draftByModel: Record<string, BomModelLineDraft>) {
    setBreakdownSaving(true)
    try {
      const rows = (await Promise.all(group.allIds.map(id => getBomItemById(id)))).filter(
        (r): r is NonNullable<typeof r> => Boolean(r)
      )
      if (rows.length === 0) throw new Error(t('common.error'))

      const { familyIds, cards } = buildBreakdownSaveCards(models, group, rows, draftByModel, stations)
      const active = cards.filter(c => {
        const q = Number(c.qty)
        return c.part_number.trim() && c.modelId && Number.isFinite(q) && q > 0
      })
      if (active.length === 0) throw new Error(t('bom.breakdownNoActive'))

      const row = rows[0]
      const names = {
        part_name_ar: row.part_name_ar ?? undefined,
        part_name_en: row.part_name_en ?? undefined,
        notes: row.notes ?? undefined,
        stopper_type: effectiveBomStopperType(row)
      }

      const usedIds = new Set<string>()
      const rowByModel = bomRowsByModelName(models, rows)

      if (cardsCanConsolidate(active)) {
        const id = await saveBomFromModelCards(group.primary.id, familyIds, cards, names, models)
        usedIds.add(id)
      } else {
        for (const card of active) {
          const existing = rowByModel.get(card.modelName)
          const eId =
            existing?.id && !usedIds.has(existing.id) ? existing.id : usedIds.size === 0 ? group.primary.id : undefined
          const famId = familyIdForModel(models, card.modelId)
          const id = await saveBomFromModelCards(eId, famId ? [famId] : familyIds, [card], names, models)
          usedIds.add(id)
        }
      }

      for (const id of group.allIds) {
        if (!usedIds.has(id)) await deleteBomItem(id)
      }

      reload(t('settings.updated'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
      throw e
    } finally {
      setBreakdownSaving(false)
    }
  }

  void openTabsKey

  const selectedName = perModel
    ? compareMode
      ? openTabsActive.join(' · ')
      : activeModelTab || t('bom.selectModel')
    : modelName || t('bom.allModels')

  return {
    t,
    models,
    stations,
    modelName,
    setModelName,
    stationId,
    setStationId,
    search,
    setSearch,
    stopperType,
    setStopperType,
    noOperationOnly,
    setNoOperationOnly,
    page,
    setPage,
    total,
    filteredCount,
    loading,
    iplRefreshing,
    formMode,
    setFormMode,
    editId,
    setEditId,
    editIds,
    setEditIds,
    deleteTarget,
    setDeleteTarget,
    deleting,
    breakdownSaving,
    iplSaving,
    expandedKeys,
    stationOptions,
    partFormOpen,
    setPartFormOpen,
    partEditId,
    partForm,
    setPartForm,
    partFormBusy,
    iplLogisticsGroup,
    setIplLogisticsGroup,
    iplDeleteTarget,
    setIplDeleteTarget,
    perModel,
    effectiveModelName,
    modelPicker,
    masterStations,
    assignableModels,
    assignableModelNames,
    openTabsActive,
    compareMode,
    scopedItems,
    displayGroups,
    pagedGroups,
    groupTotal,
    rowColumns,
    colWidths,
    colCount,
    baseFilters,
    excelFilters,
    activeExcelFilterCount,
    selectedName,
    canCreate,
    canUpdate,
    canDelete,
    compareItemsByModel,
    partsCache,
    reload,
    setColumnFilter,
    clearAllExcelFilters,
    confirmDelete,
    toggleExpanded,
    saveIplLogistics,
    onIplFieldSave,
    onIplStationChange,
    openPartCreate,
    openPartEditById,
    openPartEdit,
    submitPartForm,
    confirmIplDelete,
    saveBreakdown,
    toggleModelTab,
    toggleFamilyTabs,
    PAGE_SIZE,
    lineScope
  }
}

export type BomByModelDataReturn = ReturnType<typeof useBomByModelData>
