import type { BomItemDetail, Part } from '../Types/bom'
import { parseApplicableModelNames } from './bomQtyByModel'

export function isPendingBomItemId(id: string): boolean {
  return id.startsWith('pending:')
}

export function pendingBomItemId(partId: string): string {
  return `pending:${partId}`
}

/** Internal placeholder written because `parts.part_number` is NOT NULL — never show as real IPL data. */
export function isAutoGeneratedPartNumber(partNumber: string | null | undefined): boolean {
  return /^PART-[A-Z0-9]+$/i.test(String(partNumber ?? '').trim())
}

/** Part number for IPL UI — blanks auto-generated placeholders so the user fills real values. */
export function iplDisplayPartNumber(partNumber: string | null | undefined): string {
  const pn = String(partNumber ?? '').trim()
  if (!pn || isAutoGeneratedPartNumber(pn) || pn.toUpperCase() === 'NA') return ''
  return pn
}

/** Merge parts-list master row with optional BOM line for one IPL model view. */
export function mergePartToBomItem(part: Part, bom: BomItemDetail | undefined, modelName: string): BomItemDetail {
  if (bom && !isPendingBomItemId(bom.id)) {
    return {
      ...bom,
      part_number: iplDisplayPartNumber(bom.part_number),
      station_code_text: bom.station_code_text?.trim() || null,
      part_name_ar: part.part_name_ar ?? bom.part_name_ar,
      part_name_en: part.part_name_en ?? bom.part_name_en,
      part_name: part.part_name_ar ?? part.part_name_en ?? bom.part_name,
      vehicle_model_name: modelName
    }
  }

  // Pending: master is visible so the user can fill this model — do not copy another model's PN/station.
  return {
    id: pendingBomItemId(part.id),
    part_id: part.id,
    vehicle_model_id: null,
    station_id: null,
    part_number: '',
    part_name: part.part_name_ar ?? part.part_name_en,
    quantity: 0,
    side: null,
    position: null,
    model_family: null,
    applicable_models_text: modelName,
    station_code_text: null,
    station_category: null,
    supply_source: part.common_supply_source ?? null,
    bom_classification: null,
    qty_by_model_raw: null,
    source_file: null,
    source_sheet: null,
    source_row_number: null,
    import_line_key: null,
    needs_review: true,
    notes: null,
    raw_data: null,
    part_length: null,
    part_width: null,
    part_height: null,
    part_volume: null,
    feeding_method: null,
    packing: null,
    part_direction: null,
    rack_code: null,
    rack_size: null,
    rack_length: null,
    rack_width: null,
    rack_height: null,
    carton_qty: null,
    part_weight: null,
    carton_weight: null,
    is_active: true,
    normalized_part_number: part.normalized_part_number,
    part_name_ar: part.part_name_ar,
    part_name_en: part.part_name_en,
    part_type: part.part_type,
    part_number_new: null,
    alternative_part_no: null,
    category_code: null,
    category_name_ar: null,
    category_name_en: null,
    vehicle_model_name: modelName,
    station_number: null,
    station_name: null,
    stopper_type: 'non_stopper'
  }
}

export function partMatchesIplModel(part: Part, modelName: string): boolean {
  const target = modelName.trim().toUpperCase()
  if (!target) return false
  const stored = parseApplicableModelNames(part.applicable_models_text)
  // Must assign models explicitly in parts list — empty means not on any IPL model yet.
  if (stored.length === 0) return false
  return stored.some(n => n.trim().toUpperCase() === target)
}

/** Parts-list masters always appear in IPL Models (user fills PN/qty per model). */
export function isPartsListMaster(part: Pick<Part, 'common_name'>): boolean {
  return Boolean(part.common_name?.trim())
}
