import type { BomItemDetail } from '../Types/bom'
import type { Station } from '../Types/settings'
import { isAutoGeneratedPartNumber, iplDisplayPartNumber } from './iplModelParts'
import {
  buildStationOrderMap,
  displayBomStationCode,
  normalizeBomStationCodeText,
  resolveBomStationSortRank
} from './bomStationCode'
import { modelQtyForBomRow } from './bomQtyByModel'
import { compareTokenForFitStatus, iplFitStatusForModel, isIplCompareFitToken } from './iplFitStatus'

export type { IplFitStatus } from './iplFitStatus'
export {
  IPL_COMPARE_NOT_FITTED,
  IPL_COMPARE_UNSET,
  iplFitStatusForModel,
  isIplCompareFitToken
} from './iplFitStatus'

export type IplCompareRow = {
  key: string
  partNameAr: string
  partNameEn: string
  byModel: Map<string, BomItemDetail>
}

export type FieldCompareStatus = 'same' | 'different' | 'missing'

export type FieldCompareResult = {
  status: FieldCompareStatus
  sharedValue?: string
  byModel: { model: string; value: string }[]
}

export function partCompareNameKey(item: BomItemDetail): string {
  const ar = (item.part_name_ar ?? item.part_name ?? '').trim()
  const en = (item.part_name_en ?? '').trim()
  if (ar) return `ar:${ar.toLowerCase()}`
  if (en) return `en:${en.toLowerCase()}`
  return `id:${item.part_id}`
}

function pickBestItem(items: BomItemDetail[], model: string): BomItemDetail {
  if (items.length === 1) return items[0]
  return [...items].sort((a, b) => {
    const fitRank = (x: BomItemDetail) => {
      const s = iplFitStatusForModel(x, model)
      if (s === 'fitted') return 0
      if (s === 'not_fitted') return 1
      return 2
    }
    const fitDiff = fitRank(a) - fitRank(b)
    if (fitDiff !== 0) return fitDiff
    const autoDiff =
      (isAutoGeneratedPartNumber(a.part_number) ? 1 : 0) - (isAutoGeneratedPartNumber(b.part_number) ? 1 : 0)
    if (autoDiff !== 0) return autoDiff
    return (iplDisplayPartNumber(b.part_number) ? 1 : 0) - (iplDisplayPartNumber(a.part_number) ? 1 : 0)
  })[0]
}

function compareRowStationRank(row: IplCompareRow, orderMap: Map<string, number>): number {
  const items = [...row.byModel.values()]
  if (items.length === 0) return Number.POSITIVE_INFINITY
  return Math.min(...items.map(item => resolveBomStationSortRank(item, orderMap)))
}

function compareRowStationCode(row: IplCompareRow): string {
  for (const item of row.byModel.values()) {
    const code = displayBomStationCode(item.station_code_text || item.station_number || '')
    if (code) return code
  }
  return ''
}

/** Sort compare rows by settings station order, then station code, then Arabic name. */
export function sortIplCompareRowsByStation(rows: IplCompareRow[], stations: Station[]): IplCompareRow[] {
  if (stations.length === 0) {
    return [...rows].sort((a, b) => a.partNameAr.localeCompare(b.partNameAr, 'ar'))
  }
  const orderMap = buildStationOrderMap(stations)
  return [...rows].sort((a, b) => {
    const rankA = compareRowStationRank(a, orderMap)
    const rankB = compareRowStationRank(b, orderMap)
    if (rankA !== rankB) return rankA - rankB
    const codeCmp = compareRowStationCode(a).localeCompare(compareRowStationCode(b), undefined, {
      numeric: true,
      sensitivity: 'base'
    })
    if (codeCmp !== 0) return codeCmp
    return a.partNameAr.localeCompare(b.partNameAr, 'ar')
  })
}

export function buildIplCompareRows(
  openTabs: string[],
  itemsByModel: Map<string, BomItemDetail[]>,
  stations: Station[] = []
): IplCompareRow[] {
  const bucket = new Map<string, Map<string, BomItemDetail[]>>()

  for (const model of openTabs) {
    for (const item of itemsByModel.get(model) ?? []) {
      const nameKey = partCompareNameKey(item)
      if (!bucket.has(nameKey)) bucket.set(nameKey, new Map())
      const modelBucket = bucket.get(nameKey)!
      if (!modelBucket.has(model)) modelBucket.set(model, [])
      modelBucket.get(model)!.push(item)
    }
  }

  const rows: IplCompareRow[] = []
  for (const [nameKey, modelMap] of bucket) {
    const byModel = new Map<string, BomItemDetail>()
    let partNameAr = '—'
    let partNameEn = '—'
    for (const [model, items] of modelMap) {
      const best = pickBestItem(items, model)
      byModel.set(model, best)
      partNameAr = best.part_name_ar ?? best.part_name ?? partNameAr
      partNameEn = best.part_name_en ?? partNameEn
    }
    rows.push({ key: nameKey, partNameAr, partNameEn, byModel })
  }

  return sortIplCompareRowsByStation(rows, stations)
}

function fittedOrToken(item: BomItemDetail | undefined, model: string, fittedValue: string): string {
  const token = compareTokenForFitStatus(iplFitStatusForModel(item, model))
  return token ?? fittedValue
}

function displayRaw(raw: string, format?: (raw: string) => string): string {
  if (!raw) return '—'
  return format ? format(raw) : raw
}

function compareKey(raw: string, format?: (raw: string) => string): string {
  return displayRaw(raw, format).trim().toUpperCase()
}

function compareField(
  openTabs: string[],
  byModel: Map<string, BomItemDetail>,
  extract: (item: BomItemDetail | undefined, model: string) => string,
  format?: (raw: string) => string
): FieldCompareResult {
  const byModelEntries = openTabs.map(model => {
    const item = byModel.get(model)
    const raw = extract(item, model)
    return { model, value: displayRaw(raw, format), raw }
  })
  const listed = byModelEntries.map(({ model, value }) => ({ model, value }))

  const fitted = byModelEntries.filter(e => e.raw && !isIplCompareFitToken(e.raw))
  if (fitted.length === 0) {
    const tokens = byModelEntries.filter(e => isIplCompareFitToken(e.raw))
    if (tokens.length === 0) return { status: 'missing', byModel: listed }
    const uniqueTokens = new Set(tokens.map(e => e.raw))
    const valuesMatch = uniqueTokens.size <= 1
    return {
      status: valuesMatch ? 'same' : 'different',
      sharedValue: valuesMatch ? tokens[0].raw : undefined,
      byModel: listed
    }
  }

  const unique = new Set(fitted.map(e => compareKey(e.raw, format)))
  const valuesMatch = unique.size <= 1
  return {
    status: valuesMatch ? 'same' : 'different',
    sharedValue: valuesMatch ? displayRaw(fitted[0].raw, format) : undefined,
    byModel: listed
  }
}

export function comparePartNumbers(row: IplCompareRow, openTabs: string[]): FieldCompareResult {
  return compareField(openTabs, row.byModel, (item, model) =>
    fittedOrToken(item, model, iplDisplayPartNumber(item?.part_number))
  )
}

export function compareStations(row: IplCompareRow, openTabs: string[]): FieldCompareResult {
  return compareField(
    openTabs,
    row.byModel,
    (item, model) =>
      fittedOrToken(item, model, item?.station_code_text ? normalizeBomStationCodeText(item.station_code_text) : ''),
    raw => (isIplCompareFitToken(raw) ? raw : displayBomStationCode(raw) || raw)
  )
}

export function compareQuantities(row: IplCompareRow, openTabs: string[]): FieldCompareResult {
  return compareField(openTabs, row.byModel, (item, model) => {
    if (!item) return fittedOrToken(item, model, '')
    const qty = modelQtyForBomRow(item, model)
    return fittedOrToken(item, model, Number.isFinite(qty) && qty > 0 ? String(qty) : '')
  })
}
