import type { BomItemDetail } from '../Types/bom'
import { isAutoGeneratedPartNumber, iplDisplayPartNumber } from './iplModelParts'
import { displayBomStationCode, normalizeBomStationCodeText } from './bomStationCode'
import { modelQtyForBomRow } from './bomQtyByModel'

export type IplCompareRow = {
  key: string
  partNameAr: string
  partNameEn: string
  byModel: Map<string, BomItemDetail>
}

export type FieldCompareStatus = 'same' | 'different' | 'missing'

export type FieldCompareResult = {
  status: FieldCompareStatus
  sharedValue?: string
  byModel: { model: string; value: string }[]
}

export function partCompareNameKey(item: BomItemDetail): string {
  const ar = (item.part_name_ar ?? item.part_name ?? '').trim()
  const en = (item.part_name_en ?? '').trim()
  if (ar) return `ar:${ar.toLowerCase()}`
  if (en) return `en:${en.toLowerCase()}`
  return `id:${item.part_id}`
}

function pickBestItem(items: BomItemDetail[]): BomItemDetail {
  if (items.length === 1) return items[0]
  return [...items].sort((a, b) => {
    const score = (x: BomItemDetail) => (isAutoGeneratedPartNumber(x.part_number) ? 1 : 0)
    return score(a) - score(b)
  })[0]
}

export function buildIplCompareRows(openTabs: string[], itemsByModel: Map<string, BomItemDetail[]>): IplCompareRow[] {
  const bucket = new Map<string, Map<string, BomItemDetail[]>>()

  for (const model of openTabs) {
    for (const item of itemsByModel.get(model) ?? []) {
      const nameKey = partCompareNameKey(item)
      if (!bucket.has(nameKey)) bucket.set(nameKey, new Map())
      const modelBucket = bucket.get(nameKey)!
      if (!modelBucket.has(model)) modelBucket.set(model, [])
      modelBucket.get(model)!.push(item)
    }
  }

  const rows: IplCompareRow[] = []
  for (const [nameKey, modelMap] of bucket) {
    const byModel = new Map<string, BomItemDetail>()
    let partNameAr = '—'
    let partNameEn = '—'
    for (const [model, items] of modelMap) {
      const best = pickBestItem(items)
      byModel.set(model, best)
      partNameAr = best.part_name_ar ?? best.part_name ?? partNameAr
      partNameEn = best.part_name_en ?? partNameEn
    }
    rows.push({ key: nameKey, partNameAr, partNameEn, byModel })
  }

  return rows.sort((a, b) => a.partNameAr.localeCompare(b.partNameAr, 'ar'))
}

function compareField(
  openTabs: string[],
  byModel: Map<string, BomItemDetail>,
  extract: (item: BomItemDetail | undefined) => string,
  format?: (raw: string) => string
): FieldCompareResult {
  const byModelEntries = openTabs.map(model => {
    const item = byModel.get(model)
    const raw = extract(item)
    const value = raw ? (format ? format(raw) : raw) : '—'
    return { model, value, raw }
  })

  const present = byModelEntries.filter(e => e.raw)
  if (present.length === 0) {
    return { status: 'missing', byModel: byModelEntries.map(({ model, value }) => ({ model, value })) }
  }

  const unique = new Set(present.map(e => e.raw.toUpperCase()))
  const valuesMatch = unique.size <= 1
  const status: FieldCompareStatus = valuesMatch ? 'same' : 'different'
  const sharedValue = valuesMatch ? (format ? format(present[0].raw) : present[0].raw) : undefined

  return {
    status,
    sharedValue,
    byModel: byModelEntries.map(({ model, value }) => ({ model, value }))
  }
}

export function comparePartNumbers(row: IplCompareRow, openTabs: string[]): FieldCompareResult {
  return compareField(openTabs, row.byModel, item => iplDisplayPartNumber(item?.part_number))
}

export function compareStations(row: IplCompareRow, openTabs: string[]): FieldCompareResult {
  return compareField(
    openTabs,
    row.byModel,
    item => (item?.station_code_text ? normalizeBomStationCodeText(item.station_code_text) : ''),
    raw => displayBomStationCode(raw) || raw
  )
}

export function compareQuantities(row: IplCompareRow, openTabs: string[]): FieldCompareResult {
  const byModelEntries = openTabs.map(model => {
    const item = row.byModel.get(model)
    const qty = item ? modelQtyForBomRow(item, model) : 0
    const raw = qty > 0 ? String(qty) : ''
    return { model, value: raw || '—', raw: raw || '' }
  })

  const present = byModelEntries.filter(e => e.raw)
  if (present.length === 0) {
    return { status: 'missing', byModel: byModelEntries.map(({ model, value }) => ({ model, value })) }
  }

  const unique = new Set(present.map(e => e.raw))
  const status: FieldCompareStatus = unique.size <= 1 ? 'same' : 'different'
  const sharedValue = unique.size <= 1 ? present[0].raw : undefined

  return {
    status,
    sharedValue,
    byModel: byModelEntries.map(({ model, value }) => ({ model, value }))
  }
}
