import type { Part } from '../Types/bom'

import { isAutoGeneratedPartNumber } from './iplModelParts'

export function partListMasterKey(p: Pick<Part, 'part_name_ar' | 'part_name_en' | 'common_name' | 'id'>): string {
  const ar = p.part_name_ar?.trim().toLowerCase()
  if (ar) return `ar:${ar}`
  const cn = p.common_name?.trim().toLowerCase()
  if (cn) return `cn:${cn}`
  const en = p.part_name_en?.trim().toLowerCase()
  if (en) return `en:${en}`
  return `id:${p.id}`
}

export function scorePartMasterRow(p: Part): number {
  let score = 0
  if (p.common_name?.trim()) score += 8
  if (!isAutoGeneratedPartNumber(p.part_number)) score += 4
  if (p.common_station?.trim()) score += 2
  if (p.part_name_en?.trim()) score += 1
  return score
}

export function pickBestPartMaster(parts: Part[]): Part {
  if (parts.length === 1) return parts[0]
  return [...parts].sort((a, b) => scorePartMasterRow(b) - scorePartMasterRow(a))[0]
}

export function dedupePartListRows(parts: Part[]): Part[] {
  const groups = new Map<string, Part[]>()
  for (const part of parts) {
    const key = partListMasterKey(part)
    const bucket = groups.get(key) ?? []
    bucket.push(part)
    groups.set(key, bucket)
  }
  return [...groups.values()]
    .map(pickBestPartMaster)
    .sort((a, b) => {
      const sa = (a.common_station ?? '').localeCompare(b.common_station ?? '', undefined, { numeric: true })
      if (sa !== 0) return sa
      return (a.part_name_ar ?? a.common_name ?? '').localeCompare(b.part_name_ar ?? b.common_name ?? '', 'ar')
    })
}
