import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Plus, RefreshCcw, Search, X, Layers, Car } from 'lucide-react'
import { useLang } from '../../i18n/LanguageContext'
import { usePermissions } from '../../Context/PermissionsContext'
import { useAuth } from '../../Context/AuthContext'
import { getVehicleModels, getStations } from '../../services/settingsService'
import {
  deleteBomItem,
  deactivateAllBomItemsForPart,
  deactivateBomItemsForPartModel,
  getBomItemById,
  getBomItemsAll,
  listIplModelViewRows,
  listIplModelViewsByModels,
  saveBomFromModelCards,
  savePartMasterFromListForm,
  updateBomIplFeedingCard,
  updateBomItemStationForPart,
  updateIplModelLine,
  type BomExcelColumnFilters,
  type BomListFilters
} from '../../services/bomService'
import {
  deletePart,
  getPartById,
  getT4cIplStationOptions,
  isAutoGeneratedPartNumber,
  updatePartMaster,
  type PartListStationOption
} from '../../services/partsService'
import { applicableModelsAfterRemoval } from '../../Utils/bomQtyByModel'
import { isPendingBomItemId } from '../../Utils/iplModelParts'
import {
  BOM_IPL_MODEL_ROW_COLUMNS,
  BOM_IPL_TABLE_COL_WIDTH,
  BOM_MAIN_ROW_COLUMNS,
  BOM_TABLE_COL_WIDTH
} from '../../Utils/bomPartsColumns'
import { bomColumnLabelKey, BOM_COMPACT_HEADER_COLS } from '../../Utils/bomColumnHeader'
import { groupBomItemsForDisplay, bomItemsAsFlatGroups, type BomDisplayGroup } from '../../Utils/bomRowGroups'
import {
  bomRowsByModelName,
  buildBreakdownSaveCards,
  cardsCanConsolidate,
  familyIdForModel
} from '../../Utils/bomModelCards'
import { bomModelBreakdownLines, type BomModelLineDraft } from '../../Utils/bomModelBreakdown'
import { effectiveBomStopperType } from '../../Utils/bomStopper'
import {
  buildModelFamilyGroups,
  isSelectableVehicleModel,
  selectableVehicleModels
} from '../../Utils/vehicleModelHierarchy'
import { filterBomItemsByLineScope, filterModelFamilyPicker, type BomLineScope } from '../../Utils/bomModelScope'
import { masterStationsForBom, normalizeBomStationCodeText, sortBomDisplayGroups } from '../../Utils/bomStationCode'
import { formatStationReferenceCode } from '../../Utils/stationHierarchy'
import { BomGroupedTableRow } from './BomGroupedTableRow'
import { ExportableTable } from '../ExportableTable'
import type { BomFilterColumn } from '../../Utils/bomFilterFields'
import { BomFormModal } from './BomFormModal'
import { DEFAULT_PART_KIND, DEFAULT_SUPPLY_SOURCE } from '../../Utils/bomDefaults'
import { BomPartListFormModal, type PartListFormState, type PartListSavePayload } from './BomPartListFormModal'
import { BomIplLogisticsModal } from './BomIplLogisticsModal'
import { ExcelColumnFilter } from './ExcelColumnFilter'
import { ConfirmDialog } from '../ConfirmDialog'
import { inputCls } from '../FormField'
import { IplModelTabsBar } from './IplModelTabsBar'
import { IplModelCompareTable } from './IplModelCompareTable'
import type { BomItemDetail, Part } from '../../Types/bom'
import type { BomIplFeedingCard } from '../../Utils/iplBomLogistics'
import type { VehicleModel, Station } from '../../Types/settings'

const PAGE_SIZE = 100

const emptyPartForm = (): PartListFormState => ({
  common_station: '',
  part_name_ar: '',
  part_name_en: '',
  common_name: '',
  part_type: DEFAULT_PART_KIND,
  common_supply_source: DEFAULT_SUPPLY_SOURCE
})

export function BomByModelTab({
  notify,
  lineScope = 'main',
  viewMode = 'consolidated'
}: {
  notify: (m: string, err?: boolean) => void
  lineScope?: BomLineScope
  /** consolidated = مجمع عبر الموديلات · perModel = IPL موديل واحد */
  viewMode?: 'consolidated' | 'perModel'
}) {
  const { t } = useLang()
  const { hasRole } = useAuth()
  const { hasPermission } = usePermissions()
  const canCreate = hasRole('admin') || hasPermission('bom', 'create')
  const canUpdate = hasRole('admin') || hasPermission('bom', 'update')
  const canDelete = hasRole('admin') || hasPermission('bom', 'delete') || canUpdate

  const [models, setModels] = useState<VehicleModel[]>([])
  const [stations, setStations] = useState<Station[]>([])
  const [modelName, setModelName] = useState('')
  const [openModelTabs, setOpenModelTabs] = useState<string[]>([])
  const [activeModelTab, setActiveModelTab] = useState('')
  const [compareItemsByModel, setCompareItemsByModel] = useState<Map<string, BomItemDetail[]>>(new Map())
  const [stationId, setStationId] = useState('')
  const [search, setSearch] = useState('')
  const [searchDebounced, setSearchDebounced] = useState('')
  const [stopperType, setStopperType] = useState('')
  const [noOperationOnly, setNoOperationOnly] = useState(false)
  const [excelFilters, setExcelFilters] = useState<BomExcelColumnFilters>({})
  const [page, setPage] = useState(1)
  const [items, setItems] = useState<BomItemDetail[]>([])
  const [total, setTotal] = useState(0)
  const [filteredCount, setFilteredCount] = useState<number | null>(null)
  const [loading, setLoading] = useState(false)
  const [formMode, setFormMode] = useState<'create' | 'edit' | null>(null)
  const [editId, setEditId] = useState<string | null>(null)
  const [editIds, setEditIds] = useState<string[]>([])
  const [deleteTarget, setDeleteTarget] = useState<{
    group: BomDisplayGroup
    variant?: { id: string; modelName: string }
  } | null>(null)
  const [deleting, setDeleting] = useState(false)
  const [breakdownSaving, setBreakdownSaving] = useState(false)
  const [iplSaving, setIplSaving] = useState(false)
  const [expandedKeys, setExpandedKeys] = useState<Set<string>>(new Set())
  const [stationOptions, setStationOptions] = useState<PartListStationOption[]>([])
  const [partFormOpen, setPartFormOpen] = useState(false)
  const [partEditId, setPartEditId] = useState<string | null>(null)
  const [partForm, setPartForm] = useState<PartListFormState>(emptyPartForm)
  const [partFormBusy, setPartFormBusy] = useState(false)
  const [iplLogisticsGroup, setIplLogisticsGroup] = useState<BomDisplayGroup | null>(null)
  const [iplDeleteTarget, setIplDeleteTarget] = useState<BomDisplayGroup | null>(null)
  const [partsCache, setPartsCache] = useState<Map<string, Part>>(new Map())
  const didInitModelTabs = useRef(false)
  const loadSeq = useRef(0)

  const perModel = viewMode === 'perModel'
  const effectiveModelName = perModel ? activeModelTab : modelName
  const modelPicker = useMemo(
    () => filterModelFamilyPicker(buildModelFamilyGroups(models), lineScope),
    [models, lineScope]
  )
  const masterStations = useMemo(() => masterStationsForBom(stations), [stations])
  const assignableModels = useMemo(() => selectableVehicleModels(models), [models])
  const assignableModelNames = useMemo(() => new Set(assignableModels.map(m => m.name)), [assignableModels])
  const openTabsActive = useMemo(
    () => openModelTabs.filter(name => assignableModelNames.has(name)),
    [openModelTabs, assignableModelNames]
  )
  const openTabsKey = openTabsActive.join('\u0001')
  const compareMode = perModel && openTabsActive.length > 1
  const stationCodeForLoad = useMemo(() => {
    if (!stationId) return undefined
    const st = masterStations.find(s => s.id === stationId)
    return st ? normalizeBomStationCodeText(st.station_number) : undefined
  }, [stationId, masterStations])
  const scopedItems = useMemo(() => filterBomItemsByLineScope(items, lineScope), [items, lineScope])
  const displayGroups = useMemo(
    () =>
      sortBomDisplayGroups(
        perModel ? bomItemsAsFlatGroups(scopedItems) : groupBomItemsForDisplay(scopedItems),
        stations
      ),
    [scopedItems, stations, perModel]
  )
  const pagedGroups = useMemo(() => {
    const start = (page - 1) * PAGE_SIZE
    return displayGroups.slice(start, start + PAGE_SIZE)
  }, [displayGroups, page])
  const groupTotal = displayGroups.length

  const rowColumns = perModel ? BOM_IPL_MODEL_ROW_COLUMNS : BOM_MAIN_ROW_COLUMNS
  const colWidths = perModel ? BOM_IPL_TABLE_COL_WIDTH : BOM_TABLE_COL_WIDTH
  const colCount = rowColumns.length

  const baseFilters = useMemo((): Omit<BomListFilters, 'page' | 'pageSize'> => {
    const f: Omit<BomListFilters, 'page' | 'pageSize'> = { search: searchDebounced, excel: excelFilters }
    if (effectiveModelName) f.modelName = effectiveModelName
    if (stationId) {
      const st = masterStations.find(s => s.id === stationId)
      f.stationId = stationId
      if (st) f.stationNumber = normalizeBomStationCodeText(st.station_number)
    }
    if (stopperType) f.stopperType = stopperType as BomListFilters['stopperType']
    if (noOperationOnly) f.noOperationOnly = true
    return f
  }, [searchDebounced, effectiveModelName, stationId, masterStations, excelFilters, stopperType, noOperationOnly])

  const activeExcelFilterCount = Object.values(excelFilters).filter(v => v && v.length > 0).length

  useEffect(() => {
    const timer = window.setTimeout(() => setSearchDebounced(search.trim()), 350)
    return () => window.clearTimeout(timer)
  }, [search])

  const load = useCallback(async () => {
    const seq = ++loadSeq.current
    if (perModel && openTabsActive.length === 0) {
      if (seq !== loadSeq.current) return
      setItems([])
      setTotal(0)
      setFilteredCount(0)
      setCompareItemsByModel(new Map())
      setLoading(false)
      return
    }
    if (perModel && !compareMode && (!activeModelTab || !assignableModelNames.has(activeModelTab))) {
      if (seq !== loadSeq.current) return
      setLoading(false)
      return
    }
    setLoading(true)
    try {
      if (perModel) {
        if (compareMode) {
          const byModel = await listIplModelViewsByModels(openTabsActive, {
            search: searchDebounced,
            stationCode: stationCodeForLoad
          })
          if (seq !== loadSeq.current) return
          setCompareItemsByModel(byModel)
          setItems([])
          const uniqueParts = new Set<string>()
          for (const rows of byModel.values()) {
            for (const row of rows) uniqueParts.add(row.part_id || row.id)
          }
          setTotal(uniqueParts.size)
          setFilteredCount(uniqueParts.size)
        } else {
          const view = await listIplModelViewRows({
            modelName: activeModelTab,
            search: searchDebounced,
            stationCode: stationCodeForLoad,
            page,
            pageSize: PAGE_SIZE
          })
          if (seq !== loadSeq.current) return
          setCompareItemsByModel(new Map())
          setPartsCache(new Map())
          setItems(view.items)
          setTotal(view.total)
          setFilteredCount(view.total)
        }
      } else {
        const list = await getBomItemsAll(baseFilters)
        if (seq !== loadSeq.current) return
        setItems(list.items)
        setTotal(list.total)
        setFilteredCount(list.total)
        if (list.truncated) notify(t('bom.mergeTruncated'), true)
      }
    } catch (e) {
      if (seq !== loadSeq.current) return
      notify(e instanceof Error ? e.message : t('common.error'), true)
    } finally {
      if (seq === loadSeq.current) setLoading(false)
    }
  }, [
    baseFilters,
    notify,
    t,
    perModel,
    activeModelTab,
    openTabsKey,
    compareMode,
    searchDebounced,
    stationCodeForLoad,
    page,
    assignableModelNames,
    openTabsActive
  ])

  useEffect(() => {
    Promise.all([getVehicleModels(), getStations()])
      .then(([m, s]) => {
        setModels(m)
        setStations(s.filter(st => st.is_active))
      })
      .catch(() => notify(t('common.error'), true))
  }, [notify, t])

  useEffect(() => {
    if (!perModel) return
    setOpenModelTabs(prev => {
      const next = prev.filter(n => assignableModelNames.has(n))
      return next.length === prev.length && next.every((n, i) => n === prev[i]) ? prev : next
    })
    setActiveModelTab(prev => (assignableModelNames.has(prev) ? prev : assignableModels[0]?.name ?? ''))
  }, [perModel, assignableModels, assignableModelNames])

  useEffect(() => {
    if (!perModel) return
    const refreshModels = () => {
      void getVehicleModels()
        .then(setModels)
        .catch(() => {})
    }
    document.addEventListener('visibilitychange', refreshModels)
    return () => document.removeEventListener('visibilitychange', refreshModels)
  }, [perModel])

  useEffect(() => {
    if (!perModel || assignableModels.length === 0 || didInitModelTabs.current) return
    didInitModelTabs.current = true
    const allNames = assignableModels.map(m => m.name)
    setOpenModelTabs(allNames)
    setActiveModelTab(allNames[0] ?? '')
  }, [perModel, assignableModels])

  function toggleModelTab(name: string) {
    setOpenModelTabs(prev => {
      if (prev.includes(name)) {
        const next = prev.filter(n => n !== name)
        setActiveModelTab(cur => (cur === name ? next[0] ?? '' : cur))
        return next
      }
      setActiveModelTab(name)
      return [...prev, name].sort((a, b) => a.localeCompare(b))
    })
    setPage(1)
  }

  function closeModelTab(name: string) {
    setOpenModelTabs(prev => {
      const next = prev.filter(n => n !== name)
      setActiveModelTab(cur => (cur === name ? next[0] ?? '' : cur))
      return next
    })
    setPage(1)
  }

  useEffect(() => {
    if (!perModel) return
    void getT4cIplStationOptions()
      .then(setStationOptions)
      .catch(() => setStationOptions([]))
  }, [perModel])

  function reload(msg?: string) {
    void load().then(() => {
      if (msg) notify(msg)
    })
  }

  function setColumnFilter(col: BomFilterColumn, values: string[] | undefined) {
    setExcelFilters(prev => {
      const next = { ...prev }
      if (!values) delete next[col]
      else next[col] = values
      return next
    })
    setPage(1)
  }

  function clearAllExcelFilters() {
    setExcelFilters({})
    setPage(1)
  }

  async function confirmDelete() {
    if (!deleteTarget) return
    setDeleting(true)
    try {
      if (deleteTarget.variant) {
        await deleteBomItem(deleteTarget.variant.id)
      } else {
        for (const id of deleteTarget.group.allIds) {
          await deleteBomItem(id)
        }
      }
      setDeleteTarget(null)
      reload(t('settings.deleted'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
    } finally {
      setDeleting(false)
    }
  }

  function toggleExpanded(key: string) {
    setExpandedKeys(prev => {
      const next = new Set(prev)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })
  }

  useEffect(() => {
    void load()
  }, [load])

  async function saveIplLogistics(itemIds: string[], card: BomIplFeedingCard) {
    setIplSaving(true)
    try {
      if (perModel && iplLogisticsGroup) {
        const primaryId = iplLogisticsGroup.primary.id
        if (isPendingBomItemId(primaryId)) {
          throw new Error(t('bom.iplNeedPartNumberAndQty'))
        }
        await updateBomIplFeedingCard([primaryId], card)
      } else {
        await updateBomIplFeedingCard(itemIds, card)
      }
      reload(t('settings.updated'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
      throw e
    } finally {
      setIplSaving(false)
    }
  }

  async function onIplFieldSave(group: BomDisplayGroup, field: 'part_number' | 'qty', value: string) {
    if (!canUpdate || !effectiveModelName) return
    const part = partsCache.get(group.primary.part_id) ?? (await getPartById(group.primary.part_id))
    const vehicleModel = models.find(m => m.name === effectiveModelName)
    if (!part || !vehicleModel) return
    try {
      if (field === 'part_number') {
        await updateIplModelLine(part, effectiveModelName, vehicleModel.id, { part_number: value })
      } else {
        const quantity = Number(value)
        if (!Number.isFinite(quantity) || quantity <= 0) return
        const fresh = (await getPartById(part.id)) ?? part
        if (isAutoGeneratedPartNumber(fresh.part_number)) {
          notify(t('bom.iplNeedPartNumberFirst'), true)
          return
        }
        await updateIplModelLine(fresh, effectiveModelName, vehicleModel.id, { quantity })
      }
      reload(t('settings.updated'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
    }
  }

  async function onIplStationChange(group: BomDisplayGroup, stationCode: string) {
    if (!canUpdate || !effectiveModelName) return
    const part = partsCache.get(group.primary.part_id) ?? (await getPartById(group.primary.part_id))
    const vehicleModel = models.find(m => m.name === effectiveModelName)
    if (!part || !vehicleModel) return
    const station = masterStations.find(s => normalizeBomStationCodeText(s.station_number) === stationCode)
    try {
      await updateBomItemStationForPart(part, effectiveModelName, vehicleModel.id, stationCode, station?.id ?? null)
      reload(t('settings.updated'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
    }
  }

  async function openPartEdit(group: BomDisplayGroup) {
    const part = partsCache.get(group.primary.part_id) ?? (await getPartById(group.primary.part_id))
    if (!part) return
    setPartEditId(part.id)
    setPartForm({
      common_station: part.common_station ?? '',
      part_name_ar: part.part_name_ar ?? '',
      part_name_en: part.part_name_en ?? '',
      common_name: part.common_name ?? part.part_name_ar ?? part.part_name_en ?? '',
      part_type: part.part_type ?? DEFAULT_PART_KIND,
      common_supply_source: part.common_supply_source ?? DEFAULT_SUPPLY_SOURCE
    })
    setPartFormOpen(true)
  }

  async function submitPartForm(payload: PartListSavePayload) {
    if (!partEditId) return
    setPartFormBusy(true)
    try {
      await savePartMasterFromListForm(
        partEditId,
        {
          common_station: partForm.common_station,
          part_name_ar: partForm.part_name_ar,
          part_name_en: partForm.part_name_en,
          common_name: partForm.common_name,
          part_type: partForm.part_type,
          common_supply_source: partForm.common_supply_source
        },
        payload.cards,
        payload.models
      )
      setPartFormOpen(false)
      reload(t('settings.updated'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
    } finally {
      setPartFormBusy(false)
    }
  }

  async function confirmIplDelete() {
    if (!iplDeleteTarget || !effectiveModelName) return
    setDeleting(true)
    try {
      const partId = iplDeleteTarget.primary.part_id
      const part = partsCache.get(partId) ?? (await getPartById(partId))
      if (part && isAutoGeneratedPartNumber(part.part_number)) {
        await deactivateAllBomItemsForPart(partId)
        await deletePart(partId)
      } else if (part) {
        const next = applicableModelsAfterRemoval(
          part.applicable_models_text,
          effectiveModelName,
          assignableModels.map(m => m.name)
        )
        await updatePartMaster(partId, {
          common_station: part.common_station,
          part_name_ar: part.part_name_ar,
          part_name_en: part.part_name_en,
          common_name: part.common_name,
          model_names: next
        })
        await deactivateBomItemsForPartModel(partId, effectiveModelName)
      } else {
        await deactivateBomItemsForPartModel(partId, effectiveModelName)
      }
      setIplDeleteTarget(null)
      reload(t('settings.deleted'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
    } finally {
      setDeleting(false)
    }
  }

  async function saveBreakdown(group: BomDisplayGroup, draftByModel: Record<string, BomModelLineDraft>) {
    setBreakdownSaving(true)
    try {
      const rows = (await Promise.all(group.allIds.map(id => getBomItemById(id)))).filter(
        (r): r is NonNullable<typeof r> => Boolean(r)
      )
      if (rows.length === 0) throw new Error(t('common.error'))

      const { familyIds, cards } = buildBreakdownSaveCards(models, group, rows, draftByModel, stations)
      const active = cards.filter(c => {
        const q = Number(c.qty)
        return c.part_number.trim() && c.modelId && Number.isFinite(q) && q > 0
      })
      if (active.length === 0) throw new Error(t('bom.breakdownNoActive'))

      const row = rows[0]
      const names = {
        part_name_ar: row.part_name_ar ?? undefined,
        part_name_en: row.part_name_en ?? undefined,
        notes: row.notes ?? undefined,
        stopper_type: effectiveBomStopperType(row)
      }

      const usedIds = new Set<string>()
      const rowByModel = bomRowsByModelName(models, rows)

      if (cardsCanConsolidate(active)) {
        const id = await saveBomFromModelCards(group.primary.id, familyIds, cards, names, models)
        usedIds.add(id)
      } else {
        for (const card of active) {
          const existing = rowByModel.get(card.modelName)
          const editId =
            existing?.id && !usedIds.has(existing.id) ? existing.id : usedIds.size === 0 ? group.primary.id : undefined
          const famId = familyIdForModel(models, card.modelId)
          const id = await saveBomFromModelCards(editId, famId ? [famId] : familyIds, [card], names, models)
          usedIds.add(id)
        }
      }

      for (const id of group.allIds) {
        if (!usedIds.has(id)) await deleteBomItem(id)
      }

      reload(t('settings.updated'))
    } catch (e) {
      notify(e instanceof Error ? e.message : t('common.error'), true)
      throw e
    } finally {
      setBreakdownSaving(false)
    }
  }

  const selectedName = perModel
    ? compareMode
      ? openTabsActive.join(' · ')
      : activeModelTab || t('bom.selectModel')
    : modelName || t('bom.allModels')

  return (
    <div className="space-y-4">
      {perModel && (
        <div className="card-industrial p-4 sm:p-5">
          <div className="flex items-start gap-3">
            <div className="rounded-xl bg-orange-500/15 p-3 text-orange-300">
              <Car className="h-6 w-6" />
            </div>
            <div>
              <h3 className="text-lg font-black text-white">{t('bom.tabs.iplModels')}</h3>
              <p className="text-sm text-slate-400">{t('bom.iplModelsHint')}</p>
            </div>
          </div>
        </div>
      )}
      {viewMode === 'consolidated' && lineScope === 'main' && (
        <div className="card-industrial p-4 sm:p-5">
          <div className="flex items-start gap-3">
            <div className="rounded-xl bg-violet-500/15 p-3 text-violet-300">
              <Layers className="h-6 w-6" />
            </div>
            <div>
              <h3 className="text-lg font-black text-white">{t('bom.tabs.consolidated')}</h3>
              <p className="text-sm text-slate-400">{t('bom.consolidatedHint')}</p>
            </div>
          </div>
        </div>
      )}
      <div className="card-industrial p-4">
        <div className="flex flex-col gap-3 lg:flex-row lg:items-center">
          <label className="relative min-w-0 flex-1">
            <span className="sr-only">{t('bom.search')}</span>
            <Search className="pointer-events-none absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" />
            <input
              className={`${inputCls()} w-full ps-9`}
              value={search}
              onChange={e => {
                setSearch(e.target.value)
                setPage(1)
              }}
              placeholder={t('bom.searchPh')}
            />
          </label>
          <div className="flex flex-wrap items-center gap-2 lg:shrink-0">
            {activeExcelFilterCount > 0 && (
              <button
                type="button"
                onClick={clearAllExcelFilters}
                className="rounded-xl border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-xs font-bold text-amber-200"
              >
                <X className="inline h-3 w-3" /> {t('bom.excel.clearAllFilters', { n: activeExcelFilterCount })}
              </button>
            )}
            <button
              type="button"
              onClick={() => reload()}
              className="rounded-xl bg-slate-800 px-3 py-2 text-sm font-bold text-slate-200 hover:bg-slate-700"
            >
              <RefreshCcw className="inline h-4 w-4" /> {t('common.refresh')}
            </button>
            {canCreate && (
              <button
                type="button"
                onClick={() => {
                  setFormMode('create')
                  setEditId(null)
                  setEditIds([])
                }}
                className="rounded-xl bg-cyan-500 px-4 py-2 text-sm font-black text-slate-950 hover:bg-cyan-400"
              >
                <Plus className="inline h-4 w-4" /> {t('bom.addRow')}
              </button>
            )}
          </div>
        </div>

        {perModel ? (
          <div className="mt-3 border-t border-slate-800/80 pt-3">
            <IplModelTabsBar
              models={assignableModels}
              openTabs={openTabsActive}
              activeTab={activeModelTab}
              onToggleModel={toggleModelTab}
              onSelectTab={name => {
                setActiveModelTab(name)
                setPage(1)
              }}
              onCloseTab={closeModelTab}
            />
            <label className="mt-3 block max-w-xs">
              <span className="mb-1 block text-[10px] font-bold uppercase text-cyan-300">{t('bom.filterStation')}</span>
              <select
                className={inputCls()}
                value={stationId}
                onChange={e => {
                  setStationId(e.target.value)
                  setPage(1)
                }}
              >
                <option value="">{t('bom.allStations')}</option>
                {masterStations.map(s => (
                  <option key={s.id} value={s.id}>
                    {formatStationReferenceCode(s.station_number)} — {s.station_name}
                  </option>
                ))}
              </select>
            </label>
          </div>
        ) : (
        <div className="mt-3 grid grid-cols-1 gap-3 border-t border-slate-800/80 pt-3 sm:grid-cols-2 lg:grid-cols-4">
          <label className="block">
            <span className="mb-1 block text-[10px] font-bold uppercase text-violet-300">{t('bom.filterModel')}</span>
            <select
              className={inputCls()}
              value={modelName}
              onChange={e => {
                setModelName(e.target.value)
                setPage(1)
              }}
            >
              <option value="">{t('bom.allModels')}</option>
              {modelPicker.groups.map(g => (
                <optgroup key={g.family.id} label={g.family.name}>
                  {g.variants.filter(m => isSelectableVehicleModel(m, models)).map(m => (
                    <option key={m.id} value={m.name}>
                      {m.name}
                    </option>
                  ))}
                </optgroup>
              ))}
              {modelPicker.orphanVariants.filter(m => isSelectableVehicleModel(m, models)).map(m => (
                <option key={m.id} value={m.name}>
                  {m.name}
                </option>
              ))}
            </select>
          </label>
          <label className="block">
            <span className="mb-1 block text-[10px] font-bold uppercase text-cyan-300">{t('bom.filterStation')}</span>
            <select
              className={inputCls()}
              value={stationId}
              onChange={e => {
                setStationId(e.target.value)
                setPage(1)
              }}
            >
              <option value="">{t('bom.allStations')}</option>
              {masterStations.map(s => (
                <option key={s.id} value={s.id}>
                  {formatStationReferenceCode(s.station_number)} — {s.station_name}
                </option>
              ))}
            </select>
          </label>
          <>
            <label className="block">
              <span className="mb-1 block text-[10px] font-bold uppercase text-slate-500">
                {t('bom.stopperType')}
              </span>
              <select
                className={inputCls()}
                value={stopperType}
                onChange={e => {
                  setStopperType(e.target.value)
                  setPage(1)
                }}
              >
                <option value="">{t('common.all')}</option>
                <option value="line_stopper">{t('bom.stopperLine')}</option>
                <option value="car_stopper">{t('bom.stopperCar')}</option>
                <option value="non_stopper">{t('bom.stopperNone')}</option>
              </select>
            </label>
            <div className="flex items-end">
              <label className="flex cursor-pointer items-center gap-2 pb-2.5 text-sm text-slate-300">
                <input
                  type="checkbox"
                  className="rounded border-slate-600"
                  checked={noOperationOnly}
                  onChange={e => {
                    setNoOperationOnly(e.target.checked)
                    setPage(1)
                  }}
                />
                {t('bom.noOperationOnly')}
              </label>
            </div>
          </>
        </div>
        )}

        <p className="mt-3 border-t border-slate-800/80 pt-3 text-xs text-slate-500">
          {perModel && compareMode
            ? t('bom.iplModelCompareSummary', { models: openTabsActive.length, parts: filteredCount ?? 0 })
            : perModel && effectiveModelName
              ? t('bom.modelBomSummary', { model: selectedName, n: filteredCount ?? 0, shown: groupTotal })
              : !perModel && modelName
                ? t('bom.modelBomSummary', { model: selectedName, n: filteredCount ?? 0, shown: groupTotal })
                : lineScope === 'gd'
                  ? t('bom.gdBomSummary', { n: filteredCount ?? total, shown: groupTotal })
                  : t('bom.allBomSummary', { n: filteredCount ?? total, shown: groupTotal })}
          {activeExcelFilterCount > 0 && (
            <span className="ms-2 text-cyan-400">· {t('bom.excel.filtersActive', { n: activeExcelFilterCount })}</span>
          )}
        </p>
      </div>

      <div className="card-industrial overflow-hidden">
        {perModel && compareMode ? (
          <IplModelCompareTable openTabs={openTabsActive} itemsByModel={compareItemsByModel} loading={loading} />
        ) : (
        <ExportableTable filename="bom-parts" title={t('bom.title')} rowCount={pagedGroups.length}>
          <table className="bom-parts-table">
            <colgroup>
              {rowColumns.map(c => (
                <col key={c} style={{ width: colWidths[c as keyof typeof colWidths] }} />
              ))}
            </colgroup>
            <thead>
              <tr className="border-b border-slate-800">
                {rowColumns.map(c => {
                  if (c === 'actions') {
                    return (
                      <th key={c}>
                        <span className="bom-th-label">{t('common.actions')}</span>
                      </th>
                    )
                  }
                  const compact = BOM_COMPACT_HEADER_COLS.has(c)
                  const fullLabel = t(bomColumnLabelKey(c, false))
                  const headerLabel = compact ? t(bomColumnLabelKey(c, true)) : fullLabel
                  return (
                    <th key={c}>
                      <div className="bom-th-wrap">
                        <span className={`bom-th-label${compact ? ' bom-th-label--compact' : ''}`} title={fullLabel}>
                          {headerLabel}
                        </span>
                        {!perModel && (
                          <ExcelColumnFilter
                            column={c}
                            label={fullLabel}
                            baseFilters={baseFilters}
                            selected={excelFilters[c]}
                            onApply={v => setColumnFilter(c, v)}
                          />
                        )}
                      </div>
                    </th>
                  )
                })}
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan={colCount} className="text-slate-400">
                    {t('common.loading')}
                  </td>
                </tr>
              ) : pagedGroups.length === 0 ? (
                <tr>
                  <td colSpan={colCount} className="text-slate-400">
                    {t('bom.noModelBom')}
                  </td>
                </tr>
              ) : (
                pagedGroups.map(group => (
                  <BomGroupedTableRow
                    key={group.key}
                    group={group}
                    models={models}
                    stations={stations}
                    expanded={expandedKeys.has(group.key)}
                    onToggle={() => toggleExpanded(group.key)}
                    canUpdate={canUpdate}
                    canDelete={canDelete}
                    iplModelMode={perModel}
                    stationOptions={perModel ? stationOptions : undefined}
                    onStationChange={perModel && canUpdate ? onIplStationChange : undefined}
                    onIplFieldSave={perModel && canUpdate ? onIplFieldSave : undefined}
                    onOpenFeeding={perModel ? g => setIplLogisticsGroup(g) : undefined}
                    onDeleteRow={perModel && canDelete ? g => setIplDeleteTarget(g) : undefined}
                    onEdit={() => {
                      if (perModel) {
                        void openPartEdit(group)
                        return
                      }
                      setFormMode('edit')
                      setEditId(group.primary.id)
                      setEditIds(group.allIds)
                    }}
                    onEditVariant={id => {
                      setFormMode('edit')
                      setEditId(id)
                      setEditIds([id])
                    }}
                    onDeleteVariant={v => setDeleteTarget({ group, variant: { id: v.id, modelName: v.modelName } })}
                    onSaveBreakdown={canUpdate ? saveBreakdown : undefined}
                    onSaveIplLogistics={canUpdate ? saveIplLogistics : undefined}
                    breakdownSaving={breakdownSaving}
                    iplSaving={iplSaving}
                  />
                ))
              )}
            </tbody>
          </table>
        </ExportableTable>
        )}
      </div>

      {!compareMode && (
      <div className="flex items-center justify-between text-sm text-slate-400">
        <span>{t('bom.mergedRowCount', { rows: total, groups: groupTotal })}</span>
        <div className="flex gap-2">
          <button
            type="button"
            disabled={page <= 1}
            className="rounded-lg bg-slate-800 px-3 py-1 font-bold disabled:opacity-40"
            onClick={() => setPage(p => p - 1)}
          >
            {t('common.back')}
          </button>
          <span className="px-2 py-1">{page}</span>
          <button
            type="button"
            disabled={page * PAGE_SIZE >= groupTotal}
            className="rounded-lg bg-slate-800 px-3 py-1 font-bold disabled:opacity-40"
            onClick={() => setPage(p => p + 1)}
          >
            {t('common.next')}
          </button>
        </div>
      </div>
      )}

      <BomIplLogisticsModal
        open={Boolean(iplLogisticsGroup)}
        group={iplLogisticsGroup}
        canUpdate={canUpdate}
        saving={iplSaving}
        onClose={() => setIplLogisticsGroup(null)}
        onSave={saveIplLogistics}
      />

      <BomPartListFormModal
        open={partFormOpen}
        editId={partEditId}
        form={partForm}
        busy={partFormBusy}
        onClose={() => setPartFormOpen(false)}
        onSave={payload => void submitPartForm(payload)}
        onChange={setPartForm}
      />

      <BomFormModal
        mode={formMode === 'create' ? 'create' : 'edit'}
        itemId={editId}
        editItemIds={editIds.length > 1 ? editIds : undefined}
        open={formMode != null}
        defaultVehicleModelId={models.find(m => m.name === effectiveModelName)?.id || undefined}
        onClose={() => {
          setFormMode(null)
          setEditId(null)
          setEditIds([])
        }}
        onSaved={() => reload(t('settings.updated'))}
      />

      <ConfirmDialog
        open={Boolean(iplDeleteTarget)}
        title={t('bom.iplRemoveFromModelTitle')}
        message={t('bom.iplRemoveFromModelConfirm', {
          name: iplDeleteTarget?.summary.part_name_ar || iplDeleteTarget?.summary.part_name_en || '',
          model: effectiveModelName
        })}
        confirmLabel={t('common.delete')}
        cancelLabel={t('common.cancel')}
        busy={deleting}
        onConfirm={() => void confirmIplDelete()}
        onCancel={() => setIplDeleteTarget(null)}
      />

      <ConfirmDialog
        open={Boolean(deleteTarget)}
        title={t('bom.deleteRow')}
        message={
          deleteTarget
            ? deleteTarget.variant
              ? `${deleteTarget.group.summary.part_number} — ${deleteTarget.variant.modelName}`
              : `${deleteTarget.group.summary.part_number} — ${deleteTarget.group.summary.applicable_models_text || deleteTarget.group.summary.part_name_ar || ''}${
                  deleteTarget.group.allIds.length > 1
                    ? ` (${t('bom.deleteGroupHint', { n: deleteTarget.group.allIds.length })})`
                    : ''
                }`
            : ''
        }
        confirmLabel={t('common.delete')}
        cancelLabel={t('common.cancel')}
        busy={deleting}
        onConfirm={() => void confirmDelete()}
        onCancel={() => setDeleteTarget(null)}
      />
    </div>
  )
}
